#!/usr/bin/env python3
"""build_demo_app.py -- the interactive dashboard on /demo/, client-side.

WHAT THIS REPLACES AND WHY
--------------------------
/demo/ used to be a PNG screenshot linking out to an Apps Script /exec web app.
Every problem we hit with that traced back to the architecture, not the design:

  * The screenshot went stale. The one live on 2026-08-06 was captured 08-03 and
    still said "Automated Workflow LLC" three days after the name was dropped.
  * The real app could only be changed by `clasp push` + `clasp deploy`, and its
    DATA could only change by running buildProductDemo() from the Apps Script
    editor by hand -- `clasp run` is not configured -- so a data fix sat waiting
    on a Monday trigger.
  * It rendered in a cross-origin sandbox iframe, so our own QA gates could not
    read it, synthetic clicks could not reach it, and it could not even be
    screenshotted from this box (script.google.com rewrites /macros/s/ to
    /macros/u/N/s/ and 404s on the wrong account).
  * Apps Script cold start put a spinner in front of the flagship demo.

This version is plain HTML/CSS/JS served from our own domain. It is instant, it
is inspectable by the gates, and -- the part that actually matters -- **its data
is generated in the browser from today's date, so it can never go stale.** There
is no trigger to fire, no sheet to rebuild and no screenshot to recapture.

HOUSE RULES HONOURED HERE
-------------------------
  * "Math from formulas, narrative from templates." Every figure in the written
    summary is computed first and then interpolated. No sentence states a number
    that was not derived from the same series the chart draws.
  * No Math.random(). All variation comes from a deterministic hash keyed on the
    CALENDAR week, so the book is stable across reloads and naturally different
    as real weeks pass. (Position-keyed noise made history visibly mutate.)
  * Zero network requests after load. Same claim the free tools make.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from toolkit import PARSE_CSV_JS, XLSX_JS   # single source: /check/ injects these too

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / 'demo' / 'index.html'

START = '<!-- DEMO-APP:START (generated by _brand/build_demo_app.py -- do not edit by hand) -->'
END = '<!-- DEMO-APP:END -->'


APP_CSS = """
/* ---- interactive demo dashboard -------------------------------------- */
.dapp{--d-paper:#fff;--d-tint:#FBFAF3;--d-well:#F4F1E8;--d-ink:#211D14;
  --d-soft:#5C5645;--d-line:#E4DFD1;--d-line2:#D3CBB4;--d-green:#1E7A47;
  --d-red:#B4402F;--d-amber:#8A6A16;--d-bar:#CBC5B1;
  --d-mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
  max-width:1160px;margin:0 auto;border:1px solid var(--d-line);border-radius:14px;
  background:var(--d-paper);box-shadow:0 10px 30px rgba(33,29,20,.10);overflow:hidden;
  display:grid;grid-template-columns:212px 1fr;color:var(--d-ink);
  font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
.dapp *{box-sizing:border-box}

.dnav{background:var(--d-tint);border-right:1px solid var(--d-line);padding:1.1rem .8rem;
  display:flex;flex-direction:column;gap:.15rem;min-width:0}
.dbiz{font-size:1.06rem;font-weight:700;letter-spacing:-.015em;line-height:1.25;
  margin:0 .35rem .3rem;text-wrap:balance}
.dlive{display:flex;align-items:center;gap:.4rem;margin:0 .35rem 1rem;
  font-family:var(--d-mono);font-size:.62rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-green);font-weight:600}
.dlive i{width:6px;height:6px;border-radius:50%;background:var(--d-green);
  display:inline-block;flex:none;animation:dpulse 2.4s ease-in-out infinite}
@keyframes dpulse{0%,100%{opacity:1}50%{opacity:.35}}
.dtab{display:flex;align-items:center;gap:.55rem;width:100%;text-align:left;
  background:none;border:0;border-radius:9px;padding:.5rem .6rem;cursor:pointer;
  font:inherit;font-size:.9rem;color:var(--d-soft);position:relative}
.dtab:hover{background:var(--d-well);color:var(--d-ink)}
.dtab[aria-selected="true"]{background:var(--d-paper);color:var(--d-ink);font-weight:600;
  box-shadow:0 1px 3px rgba(33,29,20,.10);border:1px solid var(--d-line)}
.dtab:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}
.dtab .dic{width:15px;height:15px;flex:none;opacity:.75}
.dtab .dbadge{margin-left:auto;font-family:var(--d-mono);font-size:.62rem;font-weight:700;
  background:var(--d-red);color:#fff;border-radius:999px;padding:.05rem .38rem;line-height:1.5}
.dnav-foot{margin-top:auto;padding:.9rem .35rem 0;border-top:1px solid var(--d-line);
  font-family:var(--d-mono);font-size:.6rem;letter-spacing:.07em;text-transform:uppercase;
  color:var(--d-soft);line-height:1.7}
.dnav-foot a{color:inherit}

.dmain{min-width:0;display:flex;flex-direction:column}
.dtop{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;
  padding:.7rem 1.1rem;border-bottom:1px solid var(--d-line);background:var(--d-tint)}
.ddots{display:flex;gap:.3rem;margin-right:.2rem}
.ddots i{width:8px;height:8px;border-radius:50%;background:var(--d-line2);display:block}
.dcrumb{font-family:var(--d-mono);font-size:.66rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-soft);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}
.dchips{margin-left:auto;display:flex;gap:.35rem;flex-wrap:wrap}
.dchip{font-family:var(--d-mono);font-size:.62rem;letter-spacing:.06em;text-transform:uppercase;
  border:1px solid var(--d-line2);border-radius:999px;padding:.2rem .55rem;color:var(--d-soft);
  background:var(--d-paper);white-space:nowrap}
.dchip.ok{border-color:var(--d-green);color:var(--d-green)}
.dchip.warn{border-color:var(--d-amber);color:var(--d-amber);font-weight:700}

.dbody{padding:1.15rem 1.1rem 1.3rem;min-width:0}
.dh{margin:0 0 .1rem;font-size:1.5rem;letter-spacing:-.02em;font-weight:700}
.dhsub{margin:0 0 1rem;color:var(--d-soft);font-size:.87rem}

.dsum{border:1px solid var(--d-line);border-left:3px solid var(--d-green);
  border-radius:10px;background:var(--d-tint);padding:.85rem .95rem;margin:0 0 1.05rem}
.dsum-h{display:flex;align-items:center;gap:.4rem;margin:0 0 .35rem;
  font-family:var(--d-mono);font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-green);font-weight:700}
.dsum p{margin:0;font-size:.97rem;line-height:1.62;text-wrap:pretty}
.dsum b{font-weight:700}

.dkpis{display:grid;grid-template-columns:repeat(4,1fr);gap:.6rem;margin:0 0 1.05rem}
.dkpi{border:1px solid var(--d-line);border-radius:10px;padding:.7rem .8rem;background:var(--d-paper);
  min-width:0;text-align:left;font:inherit;cursor:pointer;position:relative}
.dkpi:hover{border-color:var(--d-line2);background:var(--d-tint)}
.dkpi:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}
.dkpi .dk-l{font-family:var(--d-mono);font-size:.6rem;letter-spacing:.09em;text-transform:uppercase;
  color:var(--d-soft);display:block;margin-bottom:.28rem;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}
.dkpi .dk-v{font-size:1.42rem;font-weight:800;letter-spacing:-.025em;
  font-variant-numeric:tabular-nums;display:block;line-height:1.12}
.dkpi .dk-d{font-family:var(--d-mono);font-size:.63rem;margin-top:.24rem;display:block;
  color:var(--d-soft)}
.dk-d.pos{color:var(--d-green)}
.dk-d.neg{color:var(--d-red)}

/* Hover/focus insight on a KPI tile: where the number CAME FROM. The whole
   product is "numbers you can trace", so the tile should be able to say what
   it is made of rather than only asserting a figure. */
.dkpi{overflow:visible}
.dkpi-why{position:absolute;left:0;right:0;top:100%;margin-top:.35rem;z-index:3;
  background:var(--d-paper);border:1px solid var(--d-line2);border-radius:9px;
  padding:.5rem .6rem;box-shadow:0 8px 20px rgba(33,29,20,.14);
  font-size:.78rem;line-height:1.5;color:var(--d-soft);text-align:left;
  opacity:0;visibility:hidden;transition:opacity .12s ease;pointer-events:none;
  min-width:13rem;text-wrap:pretty}
.dkpi:hover .dkpi-why,.dkpi:focus-visible .dkpi-why{opacity:1;visibility:visible}
.dkpi-why b{color:var(--d-ink)}
@media (max-width:860px){ .dkpi-why{min-width:0} }


.dgrid{display:grid;grid-template-columns:1.35fr 1fr;gap:.7rem}
.dpanel{border:1px solid var(--d-line);border-radius:10px;background:var(--d-paper);
  padding:.8rem .9rem;min-width:0}
.dph{display:flex;align-items:baseline;gap:.5rem;margin:0 0 .7rem;
  font-family:var(--d-mono);font-size:.62rem;letter-spacing:.09em;text-transform:uppercase;
  color:var(--d-soft)}
.dph b{color:var(--d-ink);font-weight:700}
.dph .dlink{margin-left:auto;color:var(--d-green);cursor:pointer;background:none;border:0;
  font:inherit;font-family:var(--d-mono);font-size:.62rem;letter-spacing:.06em;
  text-transform:uppercase;padding:0}
.dph .dlink:hover{text-decoration:underline}

/* Shared label strip: text stays in HTML so it never scales with a
   non-uniformly stretched SVG coordinate system. */
.dclabels{display:flex;gap:1.4%;margin-top:.4rem}
.dclabels .dcl{flex:1 1 0;min-width:0;text-align:center;font-family:var(--d-mono);
  font-size:.6rem;color:var(--d-soft);white-space:nowrap;overflow:hidden}
.dclabels .dcl.cur{color:var(--d-ink);font-weight:700}
/* On a phone a 13-point axis clips each label to its month. Hide slots rather
   than shrink text -- the flex positions stay put so the remaining labels still
   line up with their points, and the exact week is one tap away in the readout. */
@media (max-width:560px){
  .dclabels .dcl:not(:nth-child(4n+1)):not(:last-child){ visibility:hidden }
}

/* ---- line/area chart with a hover readout -----------------------------
   Single series over time, so: area fill, one hue, NO legend (the panel
   title names it). Marks live in SVG; every piece of text lives in HTML,
   because an SVG stretched with preserveAspectRatio="none" scales its text
   with the coordinate system and the labels came out enormous. */
.dlc{position:relative;width:100%;min-width:0}
.dlc-svg{width:100%;display:block;overflow:visible}
.dlc-grid{stroke:var(--d-line);stroke-width:1}
.dlc-area{fill:var(--d-green);opacity:.10}
.dlc-line{fill:none;stroke:var(--d-green);stroke-width:2;
  stroke-linejoin:round;stroke-linecap:round}
.dlc-hair{stroke:var(--d-line2);stroke-width:1;stroke-dasharray:3 3;opacity:0}
.dlc-dot{fill:var(--d-green);stroke:var(--d-paper);stroke-width:2;opacity:0}
.dlc.on .dlc-hair,.dlc.on .dlc-dot{opacity:1}
.dlc-hit{fill:transparent;cursor:crosshair}
.dlc:focus-visible{outline:2px solid var(--d-green);outline-offset:3px;border-radius:6px}

/* Values lead, labels follow -- the reader already knows the series and
   wants the number. */
.dlc-tip{position:absolute;top:0;transform:translateX(-50%);pointer-events:none;
  background:var(--d-paper);border:1px solid var(--d-line2);border-radius:9px;
  padding:.4rem .6rem;box-shadow:0 6px 18px rgba(33,29,20,.13);opacity:0;
  transition:opacity .1s ease;white-space:nowrap;z-index:2}
.dlc.on .dlc-tip{opacity:1}
.dlc-tip .t-v{display:block;font-size:1.02rem;font-weight:800;letter-spacing:-.015em;
  font-variant-numeric:tabular-nums;line-height:1.15}
.dlc-tip .t-l{display:block;font-family:var(--d-mono);font-size:.6rem;letter-spacing:.07em;
  text-transform:uppercase;color:var(--d-soft);margin-top:.12rem}
.dlc-tip .t-d{display:block;font-family:var(--d-mono);font-size:.62rem;margin-top:.15rem}
.dlc-tip .t-d.pos{color:var(--d-green)}
.dlc-tip .t-d.neg{color:var(--d-red)}
.dlc-tip .t-note{display:block;font-size:.68rem;color:var(--d-soft);margin-top:.15rem;
  max-width:13rem;white-space:normal}
.dlc-peak{position:absolute;transform:translate(-50%,-118%);pointer-events:none;
  font-family:var(--d-mono);font-size:.6rem;color:var(--d-soft);white-space:nowrap}


.drow{display:flex;align-items:flex-start;gap:.6rem;padding:.5rem 0;
  border-bottom:1px solid var(--d-line)}
.drow:last-child{border-bottom:0;padding-bottom:0}
.drow .dr-m{min-width:0;flex:1}
.drow .dr-n{font-weight:600;font-size:.9rem;display:block;white-space:nowrap;
  overflow:hidden;text-overflow:ellipsis}
.drow .dr-s{font-family:var(--d-mono);font-size:.62rem;letter-spacing:.045em;
  text-transform:uppercase;color:var(--d-soft);display:block;margin-top:.1rem}
.drow .dr-s.late{color:var(--d-red)}
.drow .dr-a{font-family:var(--d-mono);font-size:.88rem;font-weight:700;
  font-variant-numeric:tabular-nums;white-space:nowrap}
.dpill{background:#FDF3D4;border:1px solid #E6D08A;color:#6B5310;border-radius:5px;
  padding:.05rem .34rem;font-size:.72rem}

.dstats{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin:0 0 .85rem}
.dstat{border:1px solid var(--d-line);border-radius:9px;padding:.55rem .65rem;
  background:var(--d-tint);min-width:0}
.dstat .ds-v{font-size:1.02rem;font-weight:800;font-variant-numeric:tabular-nums;
  letter-spacing:-.015em;display:block}
.dstat .ds-l{font-family:var(--d-mono);font-size:.57rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--d-soft);display:block;margin-top:.15rem}
.ds-v.pos{color:var(--d-green)}
.ds-v.neg{color:var(--d-red)}

.dage{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin:0 0 .9rem}
.dagec{border:1px solid var(--d-line);border-radius:9px;padding:.6rem .7rem;background:var(--d-paper)}
.dagec .da-l{font-family:var(--d-mono);font-size:.58rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--d-soft)}
.dagec .da-v{font-size:1.06rem;font-weight:800;font-variant-numeric:tabular-nums;
  margin:.18rem 0 .38rem;letter-spacing:-.015em}
.dagec .da-t{height:6px;border-radius:999px;background:var(--d-well);overflow:hidden}
.dagec .da-f{height:100%;border-radius:999px;background:var(--d-green)}
.dagec.b2 .da-f{background:#C79A2E}
.dagec.b3 .da-f{background:#C2701F}
.dagec.b4 .da-f{background:var(--d-red)}

.drow .dr-act{flex:none;align-self:center;font:inherit;font-family:var(--d-mono);font-size:.6rem;
  letter-spacing:.06em;text-transform:uppercase;cursor:pointer;background:none;
  border:1px solid var(--d-line2);border-radius:999px;padding:.22rem .55rem;color:var(--d-soft);
  white-space:nowrap}
.drow .dr-act:hover{border-color:var(--d-green);color:var(--d-green)}
.drow .dr-act:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}

/* Draft panel. The whole point is that it ENDS here -- there is no send. */
.ddraft{margin:.9rem 0 0;border:1px solid var(--d-line);border-left:3px solid var(--d-green);
  border-radius:10px;background:var(--d-tint);padding:.85rem .95rem}
.ddraft.refuse{border-left-color:var(--d-red)}
.ddraft-h{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;margin:0 0 .55rem;
  font-family:var(--d-mono);font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-green);font-weight:700}
.ddraft.refuse .ddraft-h{color:var(--d-red)}
.ddraft-why{margin:0 0 .6rem;font-size:.82rem;color:var(--d-soft)}
.ddraft-mail{background:var(--d-paper);border:1px solid var(--d-line);border-radius:8px;
  padding:.7rem .8rem;font-size:.9rem;line-height:1.6}
.ddraft-sub{font-weight:700;margin:0 0 .45rem;padding-bottom:.4rem;border-bottom:1px solid var(--d-line)}
.ddraft-body{margin:0;white-space:pre-wrap;text-wrap:pretty}
.ddraft-gate{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;margin:.7rem 0 0;
  padding-top:.6rem;border-top:1px dashed var(--d-line2)}
.ddraft-gate .dgate-note{font-family:var(--d-mono);font-size:.6rem;letter-spacing:.05em;
  text-transform:uppercase;color:var(--d-soft)}
.ddraft-btn{font:inherit;font-size:.8rem;cursor:pointer;border-radius:8px;padding:.4rem .7rem;
  border:1px solid var(--d-line2);background:var(--d-paper);color:var(--d-ink)}
.ddraft-btn:hover{border-color:var(--d-green);color:var(--d-green)}
.ddraft-btn[disabled]{cursor:not-allowed;opacity:.5;border-style:dashed}
.ddraft-btn[disabled]:hover{border-color:var(--d-line2);color:var(--d-ink)}
/* ---- "run it on your own numbers" dropzone ----------------------------
   The whole funnel asks a stranger to email a file and wait a day. This does
   it in a second, in their browser, with nothing leaving the machine -- so the
   promise the site makes about privacy is demonstrated rather than described. */
.ddrop{margin:0 0 1.05rem;border:1.5px dashed var(--d-line2);border-radius:11px;
  background:var(--d-tint);padding:.8rem .9rem;display:flex;gap:.75rem;
  align-items:center;flex-wrap:wrap;transition:border-color .12s ease,background .12s ease}
.ddrop.over{border-color:var(--d-green);background:#F1F7F3}
.ddrop-m{min-width:0;flex:1}
.ddrop-t{margin:0;font-size:.92rem;font-weight:700}
.ddrop-s{margin:.15rem 0 0;font-size:.8rem;color:var(--d-soft);text-wrap:pretty}
.ddrop-b{flex:none;font:inherit;font-size:.85rem;cursor:pointer;border-radius:9px;
  padding:.45rem .8rem;border:1px solid var(--d-ink);background:var(--d-ink);color:var(--d-paper)}
.ddrop-b:hover{opacity:.88}
.ddrop-b.ghost{background:none;color:var(--d-ink);border-color:var(--d-line2)}
.ddrop-b:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}
.ddrop input[type=file]{display:none}
.dmap{margin:.55rem 0 0;font-family:var(--d-mono);font-size:.63rem;letter-spacing:.03em;
  color:var(--d-soft);line-height:1.7;width:100%}
.dmap b{color:var(--d-ink)}
.dmap .bad{color:var(--d-red)}
.dnote{margin:.85rem 0 0;font-size:.85rem;color:var(--d-soft);text-wrap:pretty}
.dnote b{color:var(--d-ink)}

.drep{display:flex;align-items:center;gap:.7rem;padding:.55rem 0;
  border-bottom:1px solid var(--d-line)}
.drep:last-child{border-bottom:0}
.drep .dp-d{font-family:var(--d-mono);font-size:.68rem;color:var(--d-soft);
  white-space:nowrap;min-width:5.4rem}
.drep .dp-t{font-size:.89rem;min-width:0;flex:1}
.drep .dp-s{font-family:var(--d-mono);font-size:.6rem;letter-spacing:.06em;
  text-transform:uppercase;color:var(--d-green);white-space:nowrap}

.dfoot{margin-top:auto;padding:.6rem 1.1rem;border-top:1px solid var(--d-line);
  background:var(--d-tint);font-family:var(--d-mono);font-size:.6rem;letter-spacing:.07em;
  text-transform:uppercase;color:var(--d-soft);display:flex;gap:.6rem;flex-wrap:wrap;
  align-items:center}
.dfoot a{color:inherit}
.dfoot .dsp{margin-left:auto}

@media (max-width:860px){
  .dapp{grid-template-columns:1fr}
  .dnav{flex-direction:row;align-items:center;gap:.3rem;overflow-x:auto;
    border-right:0;border-bottom:1px solid var(--d-line);padding:.55rem .6rem;
    -webkit-overflow-scrolling:touch;scrollbar-width:none}
  .dnav::-webkit-scrollbar{display:none}
  .dbiz,.dlive,.dnav-foot{display:none}
  .dtab{width:auto;white-space:nowrap;flex:none;padding:.42rem .7rem;font-size:.84rem}
  .dgrid{grid-template-columns:1fr}
  .dkpis{grid-template-columns:repeat(2,1fr)}
  .dstats{grid-template-columns:repeat(2,1fr)}
  .dage{grid-template-columns:repeat(2,1fr)}
  .dbody{padding:.95rem .8rem 1.1rem}
  .dh{font-size:1.28rem}
}
@media (max-width:430px){
  .dkpi .dk-v{font-size:1.22rem}
  .dtop{padding:.55rem .7rem}
  .dchips{width:100%;margin-left:0}
}
@media (prefers-reduced-motion:reduce){
  .dlive i{animation:none}
  .dchart .cb,.dchart .cv{transition:none}
}
"""


APP_HTML = """
<div class="frame-wrap">

  <div class="dapp" id="dapp">
    <nav class="dnav" role="tablist" aria-label="Dashboard sections">
      <p class="dbiz" id="d-biz">Gator Shine Exterior Cleaning</p>
      <p class="dlive"><i aria-hidden="true"></i>Live &middot; self-updating</p>

      <button class="dtab" id="tab-dashboard" role="tab" aria-selected="true"
              aria-controls="view-dashboard" data-view="dashboard" type="button">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <rect x="1.5" y="1.5" width="5.4" height="5.4" rx="1"/><rect x="9.1" y="1.5" width="5.4" height="5.4" rx="1"/>
          <rect x="1.5" y="9.1" width="5.4" height="5.4" rx="1"/><rect x="9.1" y="9.1" width="5.4" height="5.4" rx="1"/>
        </svg>Dashboard</button>

      <button class="dtab" id="tab-revenue" role="tab" aria-selected="false"
              aria-controls="view-revenue" data-view="revenue" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M1.6 11.6 5.6 6.9l3 2.6 4.9-6"/><path d="M10.6 3.5h3.4v3.4"/>
        </svg>Revenue</button>

      <button class="dtab" id="tab-receivables" role="tab" aria-selected="false"
              aria-controls="view-receivables" data-view="receivables" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M8 1.4v13.2"/><path d="M11.2 4.2H6.5a2 2 0 0 0 0 4h3a2 2 0 0 1 0 4H4.4"/>
        </svg>Receivables<span class="dbadge" id="d-arbadge">0</span></button>

      <button class="dtab" id="tab-reports" role="tab" aria-selected="false"
              aria-controls="view-reports" data-view="reports" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M3.2 1.7h6.3l3.3 3.3v9.3H3.2z"/><path d="M9.3 1.8v3.4h3.4"/>
        </svg>Reports</button>

      <div class="dnav-foot">built by <a href="/">Automated<br>Workflow</a></div>
    </nav>

    <div class="dmain">
      <div class="dtop">
        <span class="ddots" aria-hidden="true"><i></i><i></i><i></i></span>
        <span class="dcrumb" id="d-crumb">Dashboard &middot; <span id="d-asof"></span></span>
        <span class="dchips">
          <span class="dchip warn" id="d-samplechip">Sample data</span>
          <span class="dchip ok">&#9679; Self-updating</span>
          <span class="dchip" id="d-refreshed">Refreshed</span>
        </span>
      </div>

      <div class="dbody">
        <section id="view-dashboard" role="tabpanel" aria-labelledby="tab-dashboard" tabindex="0">
          <h2 class="dh" id="d-greet">Good morning.</h2>
          <p class="dhsub" id="d-greetsub"></p>

          <div class="ddrop" id="d-drop">
            <span class="ddrop-m">
              <p class="ddrop-t">Want to see this on your own numbers?</p>
              <p class="ddrop-s">Drop an <b>Excel file or CSV</b> of your invoices or jobs &mdash; any
              export with a date and an amount. <b>.xlsx works as-is</b>, no save-as-CSV step. It is
              read <b>in this browser</b>: nothing is uploaded, and you can have the network tab open
              while you do it.</p>
              <div class="dmap" id="d-map"></div>
            </span>
            <button class="ddrop-b" type="button" id="d-pick">Choose a file</button>
            <button class="ddrop-b ghost" type="button" id="d-reset" hidden>Back to sample</button>
            <input type="file" id="d-file" accept=".csv,.tsv,.txt,.xlsx,.xlsm,text/csv,text/plain">
          </div>

          <div class="dsum">
            <p class="dsum-h">&#10022; AI weekly summary &mdash; written by the dashboard, not by you</p>
            <p id="d-summary"></p>
          </div>

          <div class="dkpis" id="d-kpis"></div>

          <div class="dgrid">
            <div class="dpanel">
              <p class="dph"><b>Revenue</b> &mdash; last 6 weeks
                <button class="dlink" type="button" data-goto="revenue">Full chart &rarr;</button></p>
              <div id="d-minichart"></div>
            </div>
            <div class="dpanel">
              <p class="dph"><b>Receivables</b> &mdash; call first
                <button class="dlink" type="button" data-goto="receivables">All &rarr;</button></p>
              <div id="d-callfirst"></div>
            </div>
          </div>
        </section>

        <section id="view-revenue" role="tabpanel" aria-labelledby="tab-revenue" tabindex="0" hidden>
          <h2 class="dh">Revenue</h2>
          <p class="dhsub">Thirteen weeks of completed work, newest on the right.</p>
          <div class="dstats" id="r-stats"></div>
          <div class="dpanel"><div id="r-chart"></div></div>
          <p class="dnote" id="r-note"></p>
        </section>

        <section id="view-receivables" role="tabpanel" aria-labelledby="tab-receivables" tabindex="0" hidden>
          <h2 class="dh">Receivables</h2>
          <p class="dhsub">What you are owed, oldest first &mdash; because that is the call order.</p>
          <div class="dstats" id="a-stats"></div>
          <div class="dage" id="a-aging"></div>
          <div class="dpanel">
            <p class="dph"><b>Open invoices</b></p>
            <div id="a-list"></div>
            <div id="a-draft"></div>
          </div>
          <p class="dnote" id="a-note"></p>
        </section>

        <section id="view-reports" role="tabpanel" aria-labelledby="tab-reports" tabindex="0" hidden>
          <h2 class="dh">Reports</h2>
          <p class="dhsub">Every Monday this writes itself and lands in your inbox.</p>
          <div class="dpanel">
            <p class="dph"><b>Archive</b> &mdash; your weekly history</p>
            <div id="p-list"></div>
          </div>
          <p class="dnote">Each one is the summary at the top of the dashboard, captured the morning
          it was written, so you can see what you knew at the time rather than only what is true now.</p>
        </section>
      </div>

      <div class="dfoot">
        <span id="d-footnote">Sample data &mdash; yours runs on your numbers</span>
        <span class="dsp" id="d-perf"></span>
      </div>
    </div>
  </div>
</div>

<p class="demo-fallback" style="text-align:center;margin:14px auto 0;max-width:760px;font-size:13px;color:#5C5645">
  That&rsquo;s the real dashboard, running right here &mdash; tap the tabs and the KPI tiles.
  It builds itself from today&rsquo;s date in your browser, which is why it is never out of date.
</p>
"""


APP_JS = r"""
/* aw-demo-app -- the /demo/ dashboard. Client-side, no network after load.
   See _brand/build_demo_app.py for why this replaced the Apps Script embed. */
(function () {
  "use strict";
  var app = document.getElementById('dapp');
  if (!app) { return; }
  var t0 = (window.performance && performance.now) ? performance.now() : 0;

  /* ---- shared intake, injected from _brand/toolkit.py -------------------
     parseCSV / xlsxToRows / rowsToCSV come from the SAME source the tool
     pages use, injected at build time rather than pasted: two copies of a
     parser drift, and this repo has already been bitten by exactly that. */
__SHARED_INTAKE__

  /* ---------- deterministic variation (no Math.random) ------------------
     Keyed on the CALENDAR week, not on position in the array. A position key
     makes every week's value slide to a new date on each reload, so history
     appears to mutate; a calendar key keeps a given week stable forever and
     lets new weeks differ naturally as time passes. */
  function hash(x){ var s = Math.sin((x + 1) * 12.9898) * 43758.5453; return (s - Math.floor(s)) * 2 - 1; }
  /* Three octaves so neighbouring weeks stay correlated. Independent per-index
     noise reads as a copy-pasted zigzag; a single octave reads as a sine wave. */
  function wobble(k){ return hash(Math.floor(k/4))*0.5 + hash(Math.floor(k/2))*0.32 + hash(k)*0.18; }

  function addDays(d, n){ var x = new Date(d.getTime()); x.setDate(x.getDate() + n); return x; }
  function mondayOf(d){ var x = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    var off = (x.getDay() + 6) % 7; return addDays(x, -off); }
  function epochWeek(d){ return Math.floor(d.getTime() / 604800000); }
  function dayDiff(a, b){ return Math.round((a.getTime() - b.getTime()) / 86400000); }

  var MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function fmtDay(d){ return MON[d.getMonth()] + ' ' + d.getDate(); }
  function fmtLong(d){ return MON[d.getMonth()] + ' ' + d.getDate() + ', ' + d.getFullYear(); }
  function money(n){ return '$' + Math.round(n).toLocaleString('en-US'); }
  function pct(n){ return (n >= 0 ? '+' : '') + n.toFixed(1) + '%'; }

  /* ================= THE DATA SEAM =====================================
     Everything below renders from ONE object. Sample data is the fallback,
     not the only path -- so the same page drives a real client's numbers.

     To feed it real data, define this before the app script runs:

       window.AW_DASHBOARD_DATA = {
         business: "Acme Pressure Washing",     // string
         weeks: [                               // oldest first, Mondays
           { start: "2026-05-11", value: 12480 },
           ...
         ],
         receivables: [                         // open invoices only
           { customer: "Hogtown Brewing", amount: 4402, days: 96 },
           ...
         ],
         spend: 262,                            // month-to-date, optional
         activeCustomers: 12                    // optional
       };

     The client supplies FACTS ONLY. Every derived figure -- month-to-date,
     prior-month comparison, AR total, aging buckets, the written summary --
     is computed here from those facts, so a number cannot be right in one
     place and stale in another. That is the same rule the sheets follow:
     math from formulas, narrative from templates.

     A real integration replaces the assignment and nothing else: fetch the
     JSON, assign it, load this script. The renderer never learns where the
     numbers came from.
     ==================================================================== */
  var TODAY   = new Date();
  var CURMON  = mondayOf(TODAY);

  /* ---- sample book (the fallback when no real data is supplied) --------- */
  function buildSample(){
    var BASE   = 11500;   /* target revenue per full week (~$44-49k/mo) */
    var AMP    = 3400;    /* swing. At 1800 the octave blend regressed to the mean and every
                             bar came out the same height -- the chart looked broken. */
    var WEEKS  = 18;
    /* Gentle upward drift on top of the wobble. Without it the hash alone decides
       the shape, and for many starting weeks that is a steadily FALLING book --
       an odd thing for a sample business to model. Chosen by simulating 104
       possible "todays" rather than tuning to look good on one day, and
       deliberately NOT the setting that grows every time: a demo that can never
       show a soft week is the smooth line nobody believes. */
    var GROWTH = 0.45;

    var out = [];
    for (var w = WEEKS - 1; w >= 0; w--) {
      var start = addDays(CURMON, -7 * w);
      var age = (WEEKS - 1 - w) / (WEEKS - 1);        /* 0 = oldest, 1 = newest */
      var target = BASE * (1 + GROWTH * (age - 0.5)) + AMP * wobble(epochWeek(start));
      out.push({ start: start, value: Math.max(600, Math.round(target)) });
    }

    var CUSTOMERS = [
      'Hogtown Brewing','Sweetwater Vet Clinic','Celebration Pointe Realty','Haile Plantation HOA',
      'Depot Park Cafe','Archer Road Dental','Tioga Town Homes','Duckpond B&B','Micanopy Vintage Co.'
    ];
    /* Ages are fixed offsets so every aging bucket is populated; amounts vary
       deterministically by index. */
    var AGES = [96, 66, 47, 31, 12, 6];
    var recv = AGES.map(function (age, i) {
      return { customer: CUSTOMERS[i % CUSTOMERS.length], days: age,
               amount: 900 + Math.round((1 + hash(i * 17)) * 950) * 2 };
    });
    /* One invoice with NO DATE on it. This is not padding -- it is the case that
       forced the whole tone design: chase-email tone is derived from age, and
       here there is no age. A tool that quietly picks "friendly" is confidently
       wrong on the one invoice most likely to be a real problem. Carried as
       days:null so every age comparison has to decide about it explicitly. */
    recv.push({ customer: 'Tioga Town Homes', days: null, amount: 2180 });

    return { business: 'Gator Shine Exterior Cleaning', sample: true, hasSpend: true, weeks: out,
             receivables: recv, spend: 226 + Math.round((1 + hash(epochWeek(CURMON))) * 140),
             activeCustomers: CUSTOMERS.length + 3 };
  }

  /* ---- adopt: validate and normalise whatever was handed in -------------
     Fails LOUDLY with the offending field named. A dashboard that renders
     "$NaN", or silently drops a malformed invoice and shows a confident total
     that is quietly wrong, is worse than one that refuses -- that is the whole
     thesis of the business, so it had better hold here. */
  function adopt(raw){
    if (!raw || typeof raw !== 'object') { throw new Error('AW_DASHBOARD_DATA is not an object'); }
    if (!Array.isArray(raw.weeks) || !raw.weeks.length) {
      throw new Error('AW_DASHBOARD_DATA.weeks must be a non-empty array');
    }
    var weeks = raw.weeks.map(function (w, i) {
      var d = (w && w.start instanceof Date) ? w.start
            : new Date(String(w && w.start) + 'T00:00:00');
      if (!d || isNaN(d.getTime())) {
        throw new Error('weeks[' + i + '].start is not a date: ' + (w && w.start));
      }
      var v = Number(w.value);
      if (!isFinite(v) || v < 0) {
        throw new Error('weeks[' + i + '].value is not a non-negative number: ' + (w && w.value));
      }
      return { start: mondayOf(d), value: Math.round(v) };
    }).sort(function (a, b) { return a.start - b.start; });

    var recv = (raw.receivables || []).map(function (r, i) {
      var amt = Number(r && r.amount), days = Number(r && r.days);
      if (!isFinite(amt) || amt < 0) {
        throw new Error('receivables[' + i + '].amount is not a non-negative number: ' + (r && r.amount));
      }
      /* null/undefined days means "this invoice carries no date" -- a real and
         common state in exports, and distinct from a malformed value like
         "lots", which must still refuse. */
      var undated = (r.days === null || r.days === undefined || r.days === '');
      if (!undated && (!isFinite(days) || days < 0)) {
        throw new Error('receivables[' + i + '].days is not a non-negative number: ' + (r && r.days));
      }
      return { customer: String((r && r.customer) || 'Unnamed account'),
               amount: Math.round(amt), days: undated ? null : Math.round(days) };
    });

    var spend = Number(raw.spend);
    var cust  = Number(raw.activeCustomers);
    return {
      business: String(raw.business || 'Your business'),
      sample: false,
      hasSpend: isFinite(Number(raw.spend)) && Number(raw.spend) > 0,
      weeks: weeks,
      receivables: recv,
      spend: isFinite(spend) && spend >= 0 ? Math.round(spend) : 0,
      activeCustomers: isFinite(cust) && cust >= 0 ? Math.round(cust) : recv.length
    };
  }

  /* ---- derive the fields the renderer needs from either source ---------- */
  function decorate(book){
    book.weeks = book.weeks.map(function (wk, idx, arr) {
      var isCur = (idx === arr.length - 1) && (wk.start.getTime() === CURMON.getTime());
      /* The current week is only as far along as today, so it is not comparable
         to a finished one. Pro-rating stops the last point reading as a crash,
         and `days` is the divisor for any per-day figure -- dividing a pro-rated
         week by 7 under-counts the days that actually happened. */
      var elapsed = isCur ? Math.min(7, Math.max(1, dayDiff(TODAY, wk.start) + 1)) : 7;
      return { start: wk.start, label: fmtDay(wk.start), days: elapsed,
               value: isCur ? Math.max(1, Math.round(wk.value * elapsed / 7)) : wk.value,
               full: wk.value, partial: isCur && elapsed < 7 };
    });
    /* Undated invoices sort LAST, never first. `b.days - a.days` with a null
       yields NaN, and a NaN comparator leaves order to the engine -- an undated
       invoice could have surfaced as "call this one first" purely by accident. */
    book.receivables = book.receivables.slice().sort(function (a, b) {
      if (a.days === null && b.days === null) { return 0; }
      if (a.days === null) { return 1; }
      if (b.days === null) { return -1; }
      return b.days - a.days;
    }).map(function (r) {
      return { customer: r.customer, amount: r.amount, days: r.days,
               due: r.days === null ? null : addDays(TODAY, -r.days) };
    });
    return book;
  }

  var DATA_ERROR = null, D = null;
  try {
    D = decorate(window.AW_DASHBOARD_DATA ? adopt(window.AW_DASHBOARD_DATA) : buildSample());
  } catch (e) {
    DATA_ERROR = e && e.message ? e.message : String(e);
  }

  if (DATA_ERROR) {
    /* Refuse rather than render something confident and wrong -- and take the
       surrounding chrome down with it. A refusal sitting under a live-looking
       shell (a business name, an overdue badge, a "self-updating" pill) reads as
       a page that half-worked, which is the ambiguity the refusal exists to
       remove. */
    ['d-samplechip', 'd-arbadge'].forEach(function (id) {
      var n = document.getElementById(id); if (n) { n.hidden = true; }
    });
    var biz = document.getElementById('d-biz');
    if (biz) { biz.textContent = (window.AW_DASHBOARD_DATA && window.AW_DASHBOARD_DATA.business)
                                 ? String(window.AW_DASHBOARD_DATA.business) : 'Dashboard'; }
    var live = document.querySelector('#dapp .dlive');
    if (live) { live.textContent = 'Not loaded'; live.style.color = '#B4402F'; }
    var crumb = document.getElementById('d-crumb');
    if (crumb) { crumb.textContent = 'Data error'; }
    var chips = document.querySelector('#dapp .dchips');
    if (chips) { chips.textContent = ''; }
    var foot = document.getElementById('d-footnote');
    if (foot) { foot.textContent = 'No data rendered'; }
    var body = document.querySelector('#dapp .dbody');
    if (body) {
      body.innerHTML = '<h2 class="dh">This dashboard did not load.</h2>' +
        '<p class="dhsub">It was given data it could not trust, so it is showing you nothing ' +
        'rather than a number that might be wrong.</p>' +
        '<div class="dsum" style="border-left-color:#B4402F">' +
        '<p class="dsum-h" style="color:#B4402F">Problem with the supplied data</p>' +
        '<p><code>' + esc(DATA_ERROR) + '</code></p></div>';
    }
    return;
  }

  /* ---- derived model, RELOADABLE ---------------------------------------
     These were computed once at load. They are now reassigned by loadBook(),
     so the whole dashboard can be re-derived from a different book without
     touching a single render function -- which is what lets a visitor drop
     their own export on it. Declared with the same names in the same closure
     precisely so nothing downstream has to change. */
  var weeks, receivables, spend, activeCustomers, arTotal, undated, overdue,
      overdueTotal, mtd, pmtd, mtdDelta, neverInvoiced, netCash, openAccounts;

  function deriveFrom(book){
    D = book;
    weeks           = D.weeks;
    receivables     = D.receivables;
    spend           = D.spend;
    activeCustomers = D.activeCustomers;

    arTotal = receivables.reduce(function (s, r) { return s + r.amount; }, 0);
  /* An undated invoice is not "not overdue" -- it is UNKNOWN, and it must not
     be quietly counted either way. */
    undated = receivables.filter(function (r) { return r.days === null; });
    overdue = receivables.filter(function (r) { return r.days !== null && r.days > 30; });
    overdueTotal = overdue.reduce(function (s, r) { return s + r.amount; }, 0);

  /* Month-to-date from the weekly series: only the part of each week that falls
     inside the current calendar month. Computed, never typed. */
  /* Sum the days of the weekly series that fall inside a given calendar month,
     up to a day-of-month limit. perDay uses wk.days, not 7, so a pro-rated
     current week is not double-discounted. */
  function monthSum(monthRef, dayLimit){
    var m = monthRef.getMonth(), y = monthRef.getFullYear(), sum = 0;
    weeks.forEach(function (wk) {
      var perDay = wk.value / wk.days;
      for (var d = 0; d < wk.days; d++) {
        var day = addDays(wk.start, d);
        if (day.getMonth() === m && day.getFullYear() === y && day.getDate() <= dayLimit) { sum += perDay; }
      }
    });
    return Math.round(sum);
  }
  function monthToDate(){ return monthSum(TODAY, TODAY.getDate()); }
  /* Same day-of-month cut-off in the prior month, so it is a like-for-like
     comparison rather than a part-month against a whole one. */
  function priorMonthSame(){
    return monthSum(new Date(TODAY.getFullYear(), TODAY.getMonth() - 1, 1), TODAY.getDate());
  }

    mtd = monthToDate();
    pmtd = priorMonthSame();
    mtdDelta = pmtd > 0 ? ((mtd - pmtd) / pmtd) * 100 : 0;
  /* "Never invoiced" is the thing this whole product is pointed at: finished work
     that no one billed. Derived from the book so it moves with it. */
  /* Guard the lookback: a real book may have fewer than three weeks in it, and
     weeks[-1] would be undefined -> "$NaN" on the flagship page. */
    var recent = weeks.slice(-3, -1);
    neverInvoiced = recent.length
    ? Math.round(recent.reduce(function (a, w) { return a + w.value; }, 0) * 0.17)
    : Math.round((weeks[weeks.length - 1] || { value: 0 }).value * 0.17);
    netCash = mtd - spend;
  /* Distinct accounts carrying an open invoice -- a fact we actually hold,
     unlike crew counts. */
    openAccounts = (function () {
    var seen = {}, k = 0;
    receivables.forEach(function (r) { if (!seen[r.customer]) { seen[r.customer] = 1; k++; } });
    return k;
  })();
  }

  deriveFrom(D);

  /* ---------- rendering helpers ---------------------------------------- */
  function el(id){ return document.getElementById(id); }
  function esc(s){ return String(s).replace(/[&<>"]/g, function (c) {
    return ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' })[c]; }); }

  /* ---------- line/area chart -------------------------------------------
     Trend over time for ONE series, which the form guide answers with a line
     plus an area fill and no legend. Y starts at ZERO: a revenue trend on a
     truncated axis exaggerates every wobble into a cliff, and this dashboard
     is sold on not doing that.

     The hover layer is part of the deliverable, not an upgrade. A vertical
     hairline snaps to the nearest week, so the reader aims at a date rather
     than at a 2px line, and the readout leads with the value because they
     already know which series they are looking at. Keyboard gets the identical
     readout via arrow keys -- the tooltip enhances, it never gates: every
     figure in it is also in the stat row above.  */
  function lineChart(rows, opts){
    opts = opts || {};
    var W = 720, H = opts.h || 210, PAD = 6;
    var n = rows.length;
    var max = 0;
    rows.forEach(function (r) { if (r.value > max) { max = r.value; } });
    if (max <= 0) { max = 1; }
    var top = max * 1.10;                      /* headroom so the peak is not clipped */
    var xAt = function (i) { return n === 1 ? W / 2 : PAD + (W - PAD * 2) * (i / (n - 1)); };
    var yAt = function (v) { return H - (v / top) * H; };

    var pts = rows.map(function (r, i) { return xAt(i).toFixed(1) + ',' + yAt(r.value).toFixed(1); });
    var line = 'M' + pts.join('L');
    var area = line + 'L' + xAt(n - 1).toFixed(1) + ',' + H + 'L' + xAt(0).toFixed(1) + ',' + H + 'Z';

    var g = [];
    [0.25, 0.5, 0.75, 1].forEach(function (f) {
      var y = (H - H * f).toFixed(1);
      g.push('<line class="dlc-grid" x1="0" y1="' + y + '" x2="' + W + '" y2="' + y + '"/>');
    });

    var peakI = 0;
    rows.forEach(function (r, i) { if (r.value > rows[peakI].value) { peakI = i; } });

    var svg = '<svg class="dlc-svg" viewBox="0 0 ' + W + ' ' + H +
      '" preserveAspectRatio="none" aria-hidden="true" focusable="false">' +
      g.join('') +
      '<path class="dlc-area" d="' + area + '"/>' +
      '<path class="dlc-line" d="' + line + '" vector-effect="non-scaling-stroke"/>' +
      '<line class="dlc-hair" x1="0" y1="0" x2="0" y2="' + H + '" vector-effect="non-scaling-stroke"/>' +
      '<circle class="dlc-dot" cx="0" cy="0" r="4.5" vector-effect="non-scaling-stroke"/>' +
      '<rect class="dlc-hit" x="0" y="0" width="' + W + '" height="' + H + '"/>' +
      '</svg>';

    /* Selective direct label -- the peak only. A number on every point is
       noise, and the rest are one hover away. */
    var peak = '<span class="dlc-peak" style="left:' + (xAt(peakI) / W * 100).toFixed(2) + '%;top:' +
      (yAt(rows[peakI].value) / H * 100).toFixed(2) + '%">' + money(rows[peakI].value) + '</span>';

    var labs = rows.map(function (r, i) {
      var skip = (n > 8 && (i % 2 === 1));
      return '<span class="dcl' + (i === n - 1 ? ' cur' : '') + '">' + (skip ? '' : esc(r.label)) + '</span>';
    }).join('');

    return '<div class="dlc" tabindex="0" role="img" aria-label="' +
      esc(opts.label || 'Revenue by week') + '. Use arrow keys to read each week." data-h="' + H + '">' +
      svg + peak + '<div class="dlc-tip"></div>' +
      '<div class="dclabels" aria-hidden="true">' + labs + '</div></div>';
  }

  /* Wire hover + keyboard onto a rendered lineChart. Kept separate so the
     markup can be built as a string and the listeners attached once. */
  function wireLine(host, rows){
    var box = host.querySelector('.dlc');
    if (!box) { return; }
    var svg = box.querySelector('.dlc-svg');
    var hair = box.querySelector('.dlc-hair');
    var dot = box.querySelector('.dlc-dot');
    var tip = box.querySelector('.dlc-tip');
    var W = 720, H = Number(box.getAttribute('data-h')) || 210, PAD = 6;
    var n = rows.length;
    var max = 0;
    rows.forEach(function (r) { if (r.value > max) { max = r.value; } });
    var top = (max || 1) * 1.10;
    var idx = -1;

    function show(i){
      if (i < 0 || i >= n) { return; }
      idx = i;
      var r = rows[i];
      var x = n === 1 ? W / 2 : PAD + (W - PAD * 2) * (i / (n - 1));
      var y = H - (r.value / top) * H;
      hair.setAttribute('x1', x); hair.setAttribute('x2', x);
      dot.setAttribute('cx', x); dot.setAttribute('cy', y);
      box.classList.add('on');

      /* textContent, not innerHTML: labels are data. */
      tip.textContent = '';
      var v = document.createElement('span'); v.className = 't-v'; v.textContent = money(r.value);
      var l = document.createElement('span'); l.className = 't-l'; l.textContent = 'Week of ' + r.label;
      tip.appendChild(v); tip.appendChild(l);

      if (i > 0) {
        var prev = rows[i - 1].value;
        var diff = r.value - prev;
        var d = document.createElement('span');
        d.className = 't-d ' + (diff >= 0 ? 'pos' : 'neg');
        d.textContent = (diff >= 0 ? '+' : '−') + money(Math.abs(diff)) + ' vs the week before';
        tip.appendChild(d);
      }
      if (r.partial) {
        var note = document.createElement('span'); note.className = 't-note';
        note.textContent = 'This week is still running — it dips because it is not finished, not because takings fell.';
        tip.appendChild(note);
      }
      tip.style.left = (x / W * 100).toFixed(2) + '%';
    }
    function hide(){ box.classList.remove('on'); }

    svg.addEventListener('pointermove', function (ev) {
      var b = svg.getBoundingClientRect();
      if (!b.width) { return; }
      var rel = (ev.clientX - b.left) / b.width;              /* 0..1 across the plot */
      var i = Math.round(rel * (n - 1));
      if (i < 0) { i = 0; } if (i > n - 1) { i = n - 1; }
      show(i);
    });
    svg.addEventListener('pointerleave', hide);
    box.addEventListener('focus', function () { show(idx < 0 ? n - 1 : idx); });
    box.addEventListener('blur', hide);
    box.addEventListener('keydown', function (ev) {
      if (ev.key === 'ArrowRight') { ev.preventDefault(); show(Math.min(n - 1, idx + 1)); }
      else if (ev.key === 'ArrowLeft') { ev.preventDefault(); show(Math.max(0, idx - 1)); }
      else if (ev.key === 'Home') { ev.preventDefault(); show(0); }
      else if (ev.key === 'End') { ev.preventDefault(); show(n - 1); }
      else if (ev.key === 'Escape') { hide(); }
    });
  }

  function rowsHTML(items, withDraft){
    return items.map(function (r, i) {
      var late = r.days !== null && r.days > 30;
      var note = r.days === null
        ? 'no date on this invoice — age unknown'
        : (late ? (r.days + 'd overdue · ' + (r.days > 90 ? 'oldest open — call first'
                   : r.days > 60 ? 'crossed 60 days' : 'due ' + fmtDay(r.due)))
                : ('due ' + fmtDay(addDays(r.due, 30))));
      var amt = '<span class="dr-a">' + (r.days !== null && r.days > 90
                ? '<span class="dpill">' + money(r.amount) + '</span>'
                : money(r.amount)) + '</span>';
      var act = withDraft
        ? '<button class="dr-act" type="button" data-draft="' + i + '">Draft chase</button>'
        : '';
      return '<div class="drow"><span class="dr-m"><span class="dr-n">' + esc(r.customer) + '</span>' +
             '<span class="dr-s' + (late ? ' late' : '') + '">' + esc(note) + '</span></span>' +
             amt + act + '</div>';
    }).join('');
  }

  /* ---------- the chase drafter -----------------------------------------
     THIS IS THE POSITIONING, MADE PRESSABLE. Everything up to the send is
     automated; the send is not automated at all. A page that only *claims* a
     human gate is indistinguishable from one that quietly sends, so the gate is
     shown: there is no send control anywhere in this app, and the disabled
     control says why rather than pretending to be busy.

     Tone is derived from age. Which means that when there is NO age, tone
     cannot be derived -- and the honest move is to refuse. That is not an edge
     case bolted on for show: it is the case that forced this design, because
     the alternative is quietly picking "friendly" for the one invoice nobody
     can date, which is exactly where a wrong tone does the most damage. */
  var TONES = [
    { min: 91, key: 'firm',    label: 'Firm — final notice before escalation' },
    { min: 61, key: 'direct',  label: 'Direct — past 60 days' },
    { min: 31, key: 'neutral', label: 'Neutral — a nudge, not a chase' }
  ];

  function draftFor(r){
    if (r.days === null) { return null; }          /* no age -> no tone -> refuse */
    for (var i = 0; i < TONES.length; i++) {
      if (r.days >= TONES[i].min) { return TONES[i]; }
    }
    return null;                                    /* not yet due -> nothing to chase */
  }

  function chaseBody(r, tone){
    var amt = money(r.amount);
    var NL = String.fromCharCode(10);   /* built at runtime: keeps newline escapes
                                           out of a source file that passes through
                                           a generator, where they get eaten */
    var lines;
    if (tone.key === 'firm') {
      lines = ['Hi,', '',
        'Invoice for ' + amt + ' is now ' + r.days + ' days past due, and it is the oldest item ' +
        'open on the account.', '',
        'Could you let me know today when it will be paid, or tell me what is holding it up so I ' +
        'can help sort it? If there is a problem with the invoice itself I would rather hear that ' +
        'than keep chasing it.', '',
        'Thanks,', 'Colin'];
    } else if (tone.key === 'direct') {
      lines = ['Hi,', '',
        'Invoice for ' + amt + ' has crossed 60 days.', '',
        'Can you confirm it is in the payment run, and roughly when I should expect it? If it needs ' +
        'a PO number or a resend to a different address, just say and I will get it over.', '',
        'Thanks,', 'Colin'];
    } else {
      lines = ['Hi,', '',
        'Quick one — invoice for ' + amt + ' is ' + r.days + ' days past due.', '',
        'No drama at all if it is already scheduled; just flagging it in case it slipped through. ' +
        'Let me know if you need anything from me.', '',
        'Thanks,', 'Colin'];
    }
    return lines.join(NL);
  }

  function renderDraft(idx){
    var slot = el('a-draft');
    if (!slot) { return; }
    var r = receivables[idx];
    if (!r) { slot.innerHTML = ''; return; }
    var tone = draftFor(r);

    if (!tone) {
      var why = r.days === null
        ? 'This invoice carries <b>no date</b>, so there is no age to derive a tone from. It will not ' +
          'guess. Picking &ldquo;friendly&rdquo; here would read as confident and be unfounded &mdash; ' +
          'and an invoice nobody can date is the one most likely to be a real problem.'
        : 'This invoice is <b>not past due yet</b>. There is nothing to chase, so nothing is drafted.';
      slot.innerHTML = '<div class="ddraft refuse"><p class="ddraft-h">&#9888; No draft written &mdash; ' +
        esc(r.customer) + '</p><p class="ddraft-why">' + why + '</p>' +
        '<div class="ddraft-gate"><span class="dgate-note">A human decides what to say here</span></div></div>';
      try { slot.querySelector('.ddraft').scrollIntoView({ block: 'nearest' }); } catch (e) {}
      return;
    }

    slot.innerHTML =
      '<div class="ddraft"><p class="ddraft-h">&#10022; Drafted &mdash; ' + esc(r.customer) +
      ' <span class="dchip">' + esc(tone.label) + '</span></p>' +
      '<p class="ddraft-why">Tone derived from age: <b>' + r.days + ' days past due</b>. ' +
      'The figures come from the invoice, not from the model.</p>' +
      '<div class="ddraft-mail"><p class="ddraft-sub">Subject: ' +
      esc(tone.key === 'firm' ? 'Overdue invoice — ' + money(r.amount)
          : tone.key === 'direct' ? 'Invoice past 60 days — ' + money(r.amount)
          : 'Quick nudge — invoice for ' + money(r.amount)) + '</p>' +
      '<p class="ddraft-body">' + esc(chaseBody(r, tone)) + '</p></div>' +
      '<div class="ddraft-gate">' +
      '<button class="ddraft-btn" type="button" data-copy="' + idx + '">Copy the text</button>' +
      '<button class="ddraft-btn" type="button" disabled title="No send exists in this app">Send &mdash; not available</button>' +
      '<span class="dgate-note">It drafts. You send it, from your own inbox.</span>' +
      '</div></div>';
    try { slot.querySelector('.ddraft').scrollIntoView({ block: 'nearest' }); } catch (e) {}
  }

  function stat(v, l, tone){
    return '<div class="dstat"><span class="ds-v' + (tone ? ' ' + tone : '') + '">' + v +
           '</span><span class="ds-l">' + esc(l) + '</span></div>';
  }

  /* ---------- the written summary --------------------------------------
     HOUSE RULE: math from formulas, narrative from a template. Every number
     below is computed above and interpolated here. Nothing is estimated in
     prose, because a sentence that quietly disagrees with the chart above it
     is the exact failure this product exists to catch. */
  function summary(){
    var s = 'Revenue this month is <b>' + money(mtd) + '</b>';
    /* Only claim a comparison when there is something to compare against. With
       no prior-month data, pct() would print "+0.0% vs the same point last
       month" -- which reads as "flat", a statement about a month we have no
       data for. */
    s += pmtd > 0 ? ' (' + pct(mtdDelta) + ' vs the same point last month)'
                  : ' (no prior month to compare against yet)';

    if (arTotal > 0) {
      s += '. You are owed <b>' + money(arTotal) + '</b>';
      /* The oldest open invoice is NOT necessarily an overdue one. Asserting
         "N days past due" about an invoice that is merely N days OLD is the
         dashboard contradicting its own list, which says "due <date>" beside
         it -- the exact self-disagreement this product is sold to catch. Only
         the genuinely overdue get the chase sentence. */
      var late = overdue[0];
      if (late) {
        s += '; call <b>' + esc(late.customer) + '</b> first — ' + money(late.amount) +
             ' is ' + late.days + ' days past due';
      } else {
        s += ', and none of it is past due yet';
      }
    } else {
      s += '. Nothing is outstanding — every invoice is paid';
    }

    /* THE HONESTY GATE ON THIS WHOLE FEATURE.
       "Finished-but-never-invoiced" is a SAMPLE figure -- it comes from a
       fixed proportion of recent weeks, not from comparing jobs against
       invoices, which one file cannot support. Printing it over a stranger's
       own data would be inventing a finding about their business, which is
       precisely what this company exists not to do. Same for spend: a CSV of
       invoices does not know what they spent, and "Spending is $0" is a claim,
       not an absence. On real data both are replaced by what is actually
       missing, and by the tool that genuinely answers it. */
    if (D.sample) {
      s += '. Finished-but-never-invoiced work totals <b>' + money(neverInvoiced) +
           '</b> — invoice it this week. Spending is ' + money(spend) +
           ' this month, leaving <b>' + money(netCash) + '</b> net cash flow.';
    } else {
      s += '. ' + (D.hasSpend
        ? 'Spending is ' + money(spend) + ' this month, leaving <b>' + money(netCash) + '</b> net cash flow.'
        : 'This file has no costs in it, so there is no cash-flow figure here — that needs an expense export too.') +
        ' Work you finished but never invoiced needs your job log alongside these invoices; ' +
        '<a href="/money-leak-finder/" style="color:inherit">the money-leak tool</a> does exactly that ' +
        'comparison, also without uploading anything.';
    }
    return s;
  }

  /* ---------- views ----------------------------------------------------- */
  function renderDashboard(){
    var h = TODAY.getHours();
    el('d-greet').textContent = h < 12 ? 'Good morning.' : (h < 18 ? 'Good afternoon.' : 'Good evening.');
    el('d-greetsub').textContent = 'Here is where the business stands as of ' + fmtLong(TODAY) + '.';
    el('d-summary').innerHTML = summary();

    var kpis = [
      { l: 'Monthly revenue', v: money(mtd),
        d: pmtd > 0 ? pct(mtdDelta) + ' vs prior MTD' : 'no prior month yet',
        t: pmtd > 0 ? (mtdDelta >= 0 ? 'pos' : 'neg') : '', go: 'revenue',
        why: 'Completed work dated inside ' + MON[TODAY.getMonth()] + ', counted day by day up to ' +
             'today' + (pmtd > 0 ? '. Compared against the same day-of-month last month (' +
             money(pmtd) + '), never against a whole month' : '. No prior month in the data yet, so ' +
             'no comparison is shown rather than a misleading 0%') + '.' },
      { l: 'Outstanding AR',  v: money(arTotal),
        d: overdue.length + (overdue.length === 1 ? ' invoice past due' : ' invoices past due'),
        t: overdue.length ? 'neg' : '', go: 'receivables',
        why: 'Every open invoice added up — ' + receivables.length + ' of them. ' +
             (overdue.length ? overdue.length + ' sit past 30 days, worth ' + money(overdueTotal) + '. ' : '') +
             (undated.length ? undated.length + ' carries no date, so it is counted in the total but ' +
              'cannot be aged — it has its own column rather than being quietly filed under 0–30.'
              : 'Every one of them can be aged.') },
      (D.hasSpend
        ? { l: 'Net cash flow', v: money(netCash), d: money(spend) + ' spent this month',
            t: netCash >= 0 ? 'pos' : 'neg', go: 'revenue',
            why: 'Month-to-date revenue of <b>' + money(mtd) + '</b> minus <b>' + money(spend) +
                 '</b> of recorded spend. Cash in against cash out for this month only — not ' +
                 'profit, and it does not know about anything you have not entered.' }
        : { l: 'Net cash flow', v: '—', d: 'no costs in this file',
            t: '', go: 'revenue',
            why: 'Left blank on purpose. This file carries invoices but no costs, and showing ' +
                 'revenue here labelled &ldquo;net cash flow&rdquo; would be wrong by a whole side ' +
                 'of the ledger. Add an expense export and it fills in.' }),
      /* Was the hardcoded string "across 3 crews". Harmless on sample data and a
         FABRICATION the moment a real book is loaded -- the dashboard would be
         asserting a fact about a business it knows nothing about. Derived now. */
      { l: 'Active customers',v: String(activeCustomers),
        d: openAccounts + (openAccounts === 1 ? ' with open work' : ' with open invoices'),
        t: '', go: 'receivables',
        why: 'Accounts on the book. <b>' + openAccounts + '</b> of them currently carry an open ' +
             'invoice. Deliberately not a guess at crew counts or headcount — this only reports ' +
             'what the invoices actually show.' }
    ];
    el('d-kpis').innerHTML = kpis.map(function (k) {
      return '<button class="dkpi" type="button" data-goto="' + k.go + '">' +
             '<span class="dk-l">' + esc(k.l) + '</span>' +
             '<span class="dk-v">' + k.v + '</span>' +
             '<span class="dk-d' + (k.t ? ' ' + k.t : '') + '">' + esc(k.d) + '</span>' +
             (k.why ? '<span class="dkpi-why">' + k.why + '</span>' : '') + '</button>';
    }).join('');

    var mini = weeks.slice(-6);
    el('d-minichart').innerHTML = lineChart(mini, { h: 128, label: 'Revenue, last six weeks' });
    wireLine(el('d-minichart'), mini);
    el('d-callfirst').innerHTML = receivables.length
      ? rowsHTML(receivables.slice(0, 3))
      : '<p class="dnote" style="margin:0">Nothing outstanding — every invoice is paid.</p>';
  }

  function renderRevenue(){
    var rows = weeks.slice(-13);

    /* EVERY PERIOD STAT USES COMPLETE WEEKS ONLY.
       The newest week is only as far along as today, so including it drags an
       average down and turns an ordinary Tuesday into "revenue is falling".
       That is a measurement artifact -- the number moves without the business
       moving -- and shipping one inside a dashboard that sells honest
       measurement would be the exact thing this product exists to catch. The
       partial week still appears in the chart, where it is visibly the current
       week, because hiding it would be its own kind of lie. */
    var done = rows.filter(function (r) { return !r.partial; });
    var vals = done.map(function (r) { return r.value; });
    if (!vals.length) { vals = rows.map(function (r) { return r.value; }); done = rows; }

    var best = Math.max.apply(null, vals);
    var bestRow = done[vals.indexOf(best)];
    var avg = vals.reduce(function (a, b) { return a + b; }, 0) / vals.length;
    var half = Math.floor(vals.length / 2);
    var recent = vals.slice(half).reduce(function (a, b) { return a + b; }, 0);
    var prior  = vals.slice(0, half).reduce(function (a, b) { return a + b; }, 0);
    var above  = vals.slice(half).filter(function (v) { return v > avg; }).length;
    var delta  = recent - prior;

    el('r-stats').innerHTML =
      stat(money(best), 'Best week · ' + bestRow.label) +
      stat(money(avg), vals.length + '-wk avg / wk') +
      stat((delta >= 0 ? '+' : '') + money(delta), 'vs prior ' + half + ' wks',
           delta >= 0 ? 'pos' : 'neg') +
      stat(above + ' of ' + (vals.length - half), 'Weeks above avg');
    el('r-chart').innerHTML = lineChart(rows, { h: 210, label: 'Revenue, last thirteen weeks' });
    wireLine(el('r-chart'), rows);
    el('r-note').innerHTML = 'Best week was <b>' + bestRow.label + '</b> at ' + money(best) +
      '. The last point is the week in progress, so it dips by design rather than as a downturn — ' +
      '<b>every figure above is calculated on completed weeks only</b>, because an average that ' +
      'quietly includes a half-finished week drops every Monday and recovers by Friday, and you ' +
      'would spend months reacting to the calendar instead of the business.';
  }

  function renderReceivables(){
    var buckets = [
      /* Every filter tests days !== null FIRST. `null <= 30` is true in
         JavaScript, so an undated invoice would otherwise land silently in the
         0-30 bucket, the column totals would still reconcile, and the one
         invoice nobody can age would be the one nobody ever sees. It gets its
         own cell instead -- so the buckets still sum to AR and nothing hides. */
      { l: '0–30',  v: receivables.filter(function(r){ return r.days !== null && r.days <= 30; }) },
      { l: '31–60', v: receivables.filter(function(r){ return r.days !== null && r.days > 30 && r.days <= 60; }) },
      { l: '61–90', v: receivables.filter(function(r){ return r.days !== null && r.days > 60 && r.days <= 90; }) },
      { l: '90+',   v: receivables.filter(function(r){ return r.days !== null && r.days > 90; }) },
      { l: 'Undated', v: undated }
    ].map(function (b) { return { l: b.l, total: b.v.reduce(function(s,r){ return s+r.amount; }, 0) }; });
    var mx = Math.max.apply(null, buckets.map(function (b) { return b.total; })) || 1;
    var worst = receivables[0];

    el('a-stats').innerHTML =
      stat(money(arTotal), 'Total outstanding') +
      stat(money(overdueTotal), 'Overdue', 'neg') +
      stat(String(overdue.length), 'Invoices past due') +
      stat(worst ? worst.days + 'd' : '—', 'Oldest overdue');
    el('a-aging').innerHTML = buckets.map(function (b, i) {
      return '<div class="dagec b' + (i + 1) + '"><span class="da-l">' + b.l + ' days</span>' +
             '<span class="da-v">' + money(b.total) + '</span>' +
             '<span class="da-t"><span class="da-f" style="width:' +
             Math.max(3, Math.round(b.total / mx * 100)) + '%"></span></span></div>';
    }).join('');
    el('a-list').innerHTML = receivables.length
      ? rowsHTML(receivables, true)
      : '<p class="dnote" style="margin:0">No open invoices.</p>';
    var slot0 = el('a-draft'); if (slot0) { slot0.innerHTML = ''; }
    var lead = overdue[0];   /* the oldest OVERDUE one, not merely the oldest */
    el('a-note').innerHTML = arTotal > 0
      ? ('Of <b>' + money(arTotal) + '</b> outstanding, <b>' + money(overdueTotal) +
         '</b> is past 30 days' + (lead ? '. Start with <b>' + esc(lead.customer) + '</b> (' +
         money(lead.amount) + ', ' + lead.days + 'd late)' : ' — nothing has aged past 30 days yet') +
         '. Press <b>Draft chase</b> on any row: the tone is derived from how late it is, and then it ' +
         'stops. There is no send button in this app' +
         (undated.length ? ' — and on the invoice with no date it refuses to pick a tone at all, ' +
          'rather than guessing' : '') + '.')
      : 'Nothing is outstanding. When something ages past 30 days, the chase email drafts itself — and then waits for you to press send.';
  }

  function renderReports(){
    var out = [];
    for (var i = 0; i < 8; i++) {
      var d = addDays(CURMON, -7 * i);
      out.push('<div class="drep"><span class="dp-d">' + fmtDay(d) +
               '</span><span class="dp-t">Weekly summary — revenue, receivables and what to chase' +
               '</span><span class="dp-s">' + (i === 0 ? 'This week' : 'Sent') + '</span></div>');
    }
    el('p-list').innerHTML = out.join('');
  }

  /* ---------- tabs ------------------------------------------------------ */
  var VIEWS = ['dashboard','revenue','receivables','reports'];
  var LABEL = { dashboard:'Dashboard', revenue:'Revenue', receivables:'Receivables', reports:'Reports' };
  var rendered = {};

  function show(name){
    if (VIEWS.indexOf(name) < 0) { name = 'dashboard'; }
    VIEWS.forEach(function (v) {
      var panel = el('view-' + v), tab = el('tab-' + v), on = (v === name);
      if (panel) { panel.hidden = !on; }
      if (tab) { tab.setAttribute('aria-selected', on ? 'true' : 'false');
                 tab.tabIndex = on ? 0 : -1; }
    });
    if (!rendered[name]) {
      if (name === 'revenue') { renderRevenue(); }
      else if (name === 'receivables') { renderReceivables(); }
      else if (name === 'reports') { renderReports(); }
      rendered[name] = true;
    }
    el('d-crumb').innerHTML = LABEL[name] + ' &middot; <span id="d-asof">' + fmtLong(TODAY) + '</span>';
  }

  app.addEventListener('click', function (ev) {
    var d = ev.target.closest('[data-draft]');
    if (d && app.contains(d)) { renderDraft(Number(d.getAttribute('data-draft'))); return; }

    var c = ev.target.closest('[data-copy]');
    if (c && app.contains(c)) {
      /* Copy is a local clipboard write, not a network call -- the page's
         "0 requests after load" claim still holds, and it is the only action
         this app takes on the outside world. */
      var box = app.querySelector('.ddraft-mail');
      var text = box ? box.innerText : '';
      var done = function () { c.textContent = 'Copied'; setTimeout(function () {
        c.textContent = 'Copy the text'; }, 1600); };
      try {
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText(text).then(done, function () { c.textContent = 'Select and copy'; });
        } else { c.textContent = 'Select and copy'; }
      } catch (e) { c.textContent = 'Select and copy'; }
      return;
    }

    var t = ev.target.closest('[data-view],[data-goto]');
    if (!t || !app.contains(t)) { return; }
    var name = t.getAttribute('data-view') || t.getAttribute('data-goto');
    show(name);
    if (t.getAttribute('data-goto')) {
      var tab = el('tab-' + name);
      if (tab) { try { tab.focus(); } catch (e) {} }
    }
  });

  /* Arrow-key movement between tabs -- expected of role="tablist", and the
     thing screen-reader users notice is missing. */
  app.addEventListener('keydown', function (ev) {
    var t = ev.target;
    if (!t || !t.classList || !t.classList.contains('dtab')) { return; }
    var i = VIEWS.indexOf(t.getAttribute('data-view'));
    if (i < 0) { return; }
    var next = null;
    if (ev.key === 'ArrowRight' || ev.key === 'ArrowDown') { next = VIEWS[(i + 1) % VIEWS.length]; }
    else if (ev.key === 'ArrowLeft' || ev.key === 'ArrowUp') { next = VIEWS[(i - 1 + VIEWS.length) % VIEWS.length]; }
    else if (ev.key === 'Home') { next = VIEWS[0]; }
    else if (ev.key === 'End') { next = VIEWS[VIEWS.length - 1]; }
    if (!next) { return; }
    ev.preventDefault();
    show(next);
    var tab = el('tab-' + next);
    if (tab) { try { tab.focus(); } catch (e) {} }
  });

  /* ================= RUN IT ON YOUR OWN NUMBERS =========================
     Reads a CSV in the browser and rebuilds the dashboard from it. No upload,
     no server, no library -- the same architecture claim every tool page makes,
     demonstrated on the flagship instead of described.

     It REFUSES rather than guesses. A date column and an amount column are the
     two things it cannot work without, and if it cannot find them with
     confidence it says which one is missing and leaves the sample data up. A
     dashboard confidently drawn from columns it misread is worse than one that
     admits it could not read them -- and it would be the exact failure this
     business sells against, committed on our own demo. */

  /* Looks like a calendar date rather than money: two separators between
     digit groups, or a month name. Needed by BOTH parsers below, which is
     why it lives here rather than inside either one. */
  function looksLikeDate(t){
    return /^\s*\d{1,4}[-\/.]\d{1,2}[-\/.]\d{1,4}/.test(t) ||
           /(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i.test(t);
  }

  function parseNum(v){
    if (v === null || v === undefined) { return null; }
    var raw = String(v).trim();
    /* A DATE IS NOT AN AMOUNT. Stripping separators out of "2026-07-01" yields
       20260701, which sails through every numeric test -- that is exactly how
       the date column got selected as the amount column, and the dashboard
       would have drawn confident revenue out of calendar dates. */
    if (looksLikeDate(raw)) { return null; }
    var t = raw.replace(/[^0-9.\-]/g, '');
    if (!t || t === '-' || t === '.') { return null; }
    var n = parseFloat(t);
    if (!isFinite(n)) { return null; }
    /* (1,234) is accounting notation for negative. */
    return /\(/.test(raw) ? -n : n;
  }

  function parseWhen(v){
    if (!v) { return null; }
    var t = String(v).trim();
    var m = t.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);
    if (m) { return new Date(+m[1], +m[2] - 1, +m[3]); }
    m = t.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{2,4})/);
    if (m) {
      var y = +m[3];
      if (y < 100) { y += 2000; }
      /* Ambiguous d/m vs m/d. US order is assumed, and the mapping line says
         which column was used so a wrong read is visible rather than silent. */
      return new Date(y, +m[1] - 1, +m[2]);
    }
    /* A BARE NUMBER IS NOT A DATE. new Date("1200") is the year 1200, so an
       amount column full of round numbers reads as 60%+ parseable dates and
       gets picked as the date column. Require something date-shaped before
       handing the string to Date(). */
    if (!looksLikeDate(t)) { return null; }
    var d = new Date(t);
    return isNaN(d.getTime()) ? null : d;
  }

  /* Name match first, then CONTENT validation -- a column called "Date" full of
     job numbers is not a date column. Same two-stage rule the tool pages use. */
  function pickCol(header, rows, namePat, test, minFrac){
    function frac(ix){
      var vals = [];
      rows.forEach(function (r) {
        var v = r[ix];
        if (v !== undefined && String(v).trim() !== '') { vals.push(v); }
      });
      if (!vals.length) { return 0; }
      var ok = 0;
      vals.forEach(function (v) { if (test(v)) { ok++; } });
      return ok / vals.length;
    }
    var byName = -1;
    for (var i = 0; i < header.length; i++) {
      if (byName < 0 && namePat.test(header[i])) { byName = i; }
    }
    if (byName >= 0 && frac(byName) > minFrac) { return byName; }
    var best = -1, bestF = 0;
    for (var j = 0; j < header.length; j++) {
      var f = frac(j);
      if (f > bestF) { bestF = f; best = j; }
    }
    return bestF > minFrac ? best : -1;
  }

  function bookFromCSV(text, fileName){
    var grid = parseCSV(text);
    if (grid.length < 2) { throw new Error('that file has no rows under its header'); }
    var header = grid[0].map(function (h) { return String(h || '').trim(); });
    var rows = [];
    grid.slice(1).forEach(function (r) { if (r.join('').trim() !== '') { rows.push(r); } });
    if (!rows.length) { throw new Error('that file has a header but no data rows'); }

    var di = pickCol(header, rows, /date|day|issued|invoiced|completed|created/i,
                     function (v) { return parseWhen(v) !== null; }, 0.6);
    var ai = pickCol(header, rows, /amount|total|value|price|revenue|charge|due|net|subtotal/i,
                     function (v) { var n = parseNum(v); return n !== null && n !== 0; }, 0.6);
    if (di < 0) { throw new Error('no column in that file reads as a date'); }
    if (ai < 0) { throw new Error('no column in that file reads as an amount'); }
    /* Belt and braces: one column cannot be both. If the detectors ever agree
       again, refuse rather than plot a column against itself. */
    if (ai === di) { throw new Error('only one usable column was found (' + header[di] +
                                     '), so there is nothing to plot against the date'); }

    var ci = -1;
    for (var k = 0; k < header.length; k++) {
      if (/client|customer|account|company|payer|name/i.test(header[k])) { ci = k; break; }
    }
    /* An explicit paid/status column lets open invoices be split out. Without
       one, receivables are NOT invented -- the mapping line says so. */
    var si = -1;
    for (var p = 0; p < header.length; p++) {
      if (/paid|status|state|settled/i.test(header[p])) { si = p; break; }
    }

    var byWeek = {}, open = [], used = 0, skipped = 0;
    rows.forEach(function (r) {
      var d = parseWhen(r[di]), n = parseNum(r[ai]);
      if (d === null || n === null) { skipped++; return; }
      used++;
      if (si >= 0 && n > 0) {
        var sv = String(r[si] || '').trim().toLowerCase();
        var settled = (sv === 'paid' || sv === 'yes' || sv === 'y' || sv === 'true' ||
                       sv === 'settled' || sv === 'complete' || sv === 'closed' || sv === '1');
        if (!settled) {
          open.push({ customer: ci >= 0 ? String(r[ci] || 'Unnamed account') : 'Unnamed account',
                      amount: n, days: Math.max(0, dayDiff(TODAY, d)) });
        }
      }
      var key = mondayOf(d).getTime();
      byWeek[key] = (byWeek[key] || 0) + n;
    });
    if (!used) { throw new Error('the columns were found, but no row had both a readable date and amount'); }

    var keys = [];
    for (var kk in byWeek) { if (byWeek.hasOwnProperty(kk)) { keys.push(Number(kk)); } }
    keys.sort(function (a, b) { return a - b; });

    /* Fill gaps: a week with no work is a real zero, and dropping it would
       compress the timeline and quietly flatter the trend. */
    var out = [], cur = keys[0], last = keys[keys.length - 1], guard = 0;
    while (cur <= last && guard++ < 400) {
      out.push({ start: new Date(cur), value: Math.max(0, Math.round(byWeek[cur] || 0)) });
      cur += 604800000;
    }
    if (out.length > 26) { out = out.slice(-26); }

    var names = {}, nOpen = 0;
    open.forEach(function (o) { if (!names[o.customer]) { names[o.customer] = 1; nOpen++; } });

    var label = fileName.replace(/\.[a-z0-9]+$/i, '').slice(0, 48) || 'Your business';
    return {
      book: { business: label, weeks: out, receivables: open.slice(0, 40), spend: 0,
              hasSpend: false, activeCustomers: nOpen },
      map: { date: header[di], amount: header[ai],
             customer: ci >= 0 ? header[ci] : null,
             status: si >= 0 ? header[si] : null,
             used: used, skipped: skipped, weeks: out.length, open: open.length }
    };
  }

  function mapLine(m){
    var bits = ['Read <b>' + m.used + '</b> rows into <b>' + m.weeks + '</b> weeks',
                'date &rarr; <b>' + esc(m.date) + '</b>',
                'amount &rarr; <b>' + esc(m.amount) + '</b>'];
    bits.push('customer &rarr; ' + (m.customer
      ? '<b>' + esc(m.customer) + '</b>'
      : '<span class="bad">not found</span>'));
    bits.push(m.status
      ? 'open invoices from <b>' + esc(m.status) + '</b> (' + m.open + ')'
      : '<span class="bad">no paid/status column &mdash; receivables left empty rather than invented</span>');
    if (m.skipped) {
      bits.push('<span class="bad">' + m.skipped + ' row(s) skipped: unreadable date or amount</span>');
    }
    return bits.join(' &middot; ') + '<br>Read it wrong? Rename the column and drop it again.';
  }

  function applyBook(book, mapHTML){
    deriveFrom(decorate(book));
    rendered = {};                       /* force every tab to re-render */
    var chip = el('d-samplechip'); if (chip) { chip.hidden = true; }
    var biz = el('d-biz'); if (biz) { biz.textContent = book.business; }
    var fn = el('d-footnote');
    if (fn) { fn.textContent = book.business + ' · your data, read in this browser'; }
    var rst = el('d-reset'); if (rst) { rst.hidden = false; }
    var bdg2 = el('d-arbadge');
    if (bdg2) { bdg2.textContent = String(overdue.length); bdg2.hidden = !overdue.length; }
    el('d-map').innerHTML = mapHTML;
    renderDashboard();
    show('dashboard');
  }

  var XLSX_NAME = new RegExp('[.](xlsx|xlsm)$', 'i');

  (function wireDrop(){
    var zone = el('d-drop'), input = el('d-file'), pick = el('d-pick'), reset = el('d-reset');
    if (!zone || !input) { return; }

    function fail(msg){
      el('d-map').innerHTML = '<span class="bad">Could not use that file &mdash; ' + esc(msg) +
        '.</span><br>The sample data is still on screen and nothing was changed. It needs one column ' +
        'that reads as a date and one that reads as an amount.';
    }
    function use(text, name){
      try {
        var r = bookFromCSV(text, name);
        applyBook(r.book, mapLine(r.map));
      } catch (e) { fail(e && e.message ? e.message : 'it could not be parsed'); }
    }
    function take(file){
      if (!file) { return; }
      if (file.size > 8 * 1024 * 1024) { fail('that file is over 8MB'); return; }
      var fr = new FileReader();
      fr.onerror = function () { fail('the file could not be read'); };
      /* .xlsx is unzipped and parsed HERE, in the browser, by the same reader the
         tool pages use. "Save it as CSV first" is the instruction this site itself
         calls the place where prospects quietly leave, so the flagship demo had
         better not require it. The toolkit's readAny() alerts on failure; its
         primitives are used directly instead, so a bad workbook lands in the same
         in-page message as every other refusal. */
      if (XLSX_NAME.test(file.name)) {
        fr.onload = function () {
          xlsxToRows(fr.result).then(function (rows) {
            if (!rows || !rows.length) { fail('that workbook has no readable sheet'); return; }
            use(rowsToCSV(rows), file.name);
          })['catch'](function (err) {
            fail('that file could not be read as an Excel workbook (' +
                 (err && err.message ? err.message : 'unknown') +
                 '); a very old .xls needs saving as .xlsx or CSV first');
          });
        };
        fr.readAsArrayBuffer(file);
        return;
      }
      fr.onload = function () { use(String(fr.result || ''), file.name); };
      fr.readAsText(file);
    }

    pick.addEventListener('click', function () { input.click(); });
    input.addEventListener('change', function () {
      take(input.files && input.files[0]);
      input.value = '';
    });
    ['dragenter', 'dragover'].forEach(function (t) {
      zone.addEventListener(t, function (ev) { ev.preventDefault(); zone.classList.add('over'); });
    });
    ['dragleave', 'drop'].forEach(function (t) {
      zone.addEventListener(t, function (ev) { ev.preventDefault(); zone.classList.remove('over'); });
    });
    zone.addEventListener('drop', function (ev) {
      var f = ev.dataTransfer && ev.dataTransfer.files && ev.dataTransfer.files[0];
      take(f);
    });
    reset.addEventListener('click', function () {
      deriveFrom(decorate(buildSample()));
      rendered = {};
      el('d-map').innerHTML = '';
      reset.hidden = true;
      var chip2 = el('d-samplechip'); if (chip2) { chip2.hidden = false; }
      var bdg3 = el('d-arbadge');
      if (bdg3) { bdg3.textContent = String(overdue.length); bdg3.hidden = !overdue.length; }
      var biz = el('d-biz'); if (biz) { biz.textContent = D.business; }
      var fn = el('d-footnote');
      if (fn) { fn.textContent = 'Sample data — yours runs on your numbers'; }
      renderDashboard();
      show('dashboard');
    });
  })();

  /* ---------- boot ------------------------------------------------------ */
  /* Name and the "Sample data" chip follow the DATA, so a real book renders as
     itself and does not sit under a label calling it a sample. */
  el('d-biz').textContent = D.business;
  /* Hidden, never removed: the visitor can load their own file and then go
     back to the sample, and a chip torn out of the DOM cannot return. */
  var chip = el('d-samplechip');
  if (chip) { chip.hidden = !D.sample; }
  var fn = el('d-footnote');
  if (fn && !D.sample) { fn.textContent = D.business + ' · live data'; }
  /* A red alert badge showing 0 is an alarm about nothing -- remove it when
     there is nothing overdue, which is the state a healthy client is in. */
  var bdg = el('d-arbadge');
  if (bdg) { bdg.textContent = String(overdue.length); bdg.hidden = !overdue.length; }
  el('d-refreshed').textContent = 'Built ' +
    TODAY.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  renderDashboard();
  show('dashboard');

  if (t0) {
    var ms = Math.max(1, Math.round(performance.now() - t0));
    el('d-perf').textContent = 'Built in ' + ms + 'ms · 0 requests';
  } else {
    el('d-perf').textContent = '0 requests after load';
  }
})();
"""


def main() -> None:
    s = PAGE.read_text(encoding='utf-8')

    app_js = APP_JS.replace('__SHARED_INTAKE__',
                            PARSE_CSV_JS.strip() + chr(10) + chr(10) + XLSX_JS.strip())
    if 'function xlsxToRows' not in app_js or 'function parseCSV' not in app_js:
        raise SystemExit('shared intake failed to inject -- did toolkit.py change?')
    block = (START + '\n<style>' + APP_CSS + '</style>\n'
             + APP_HTML + '\n<script>' + app_js + '</script>\n' + END)

    if START in s:
        # Idempotent path: swap whatever is between the markers. Re-running with
        # an unchanged template legitimately produces a byte-identical file, so
        # "no change" is a pass here, not a failure -- only a missing END marker
        # (i.e. nothing actually matched) is worth stopping for.
        s, n = re.subn(re.escape(START) + r'.*?' + re.escape(END), lambda _m: block, s, flags=re.S)
        if n != 1:
            raise SystemExit('expected exactly one marker block, matched %d' % n)
    else:
        # First run: take out the screenshot + its caption and drop the app in.
        m = re.search(r'  <div class="frame-wrap">.*?</div>\s*\n\s*<p class="demo-fallback".*?</p>\n',
                      s, flags=re.S)
        if not m:
            raise SystemExit('could not find the frame-wrap/demo-fallback block to replace')
        s = s[:m.start()] + block + '\n' + s[m.end():]

    PAGE.write_text(s, encoding='utf-8')
    print('wrote %s (%d bytes)' % (PAGE, len(s)))


if __name__ == '__main__':
    main()
