#!/usr/bin/env python3
"""build_demo_app.py -- the interactive dashboard on /demo/, client-side.

WHAT THIS REPLACES AND WHY
--------------------------
/demo/ used to be a PNG screenshot linking out to an Apps Script /exec web app.
Every problem we hit with that traced back to the architecture, not the design:

  * The screenshot went stale. The one live on 2026-08-06 was captured 08-03 and
    still said "Automated Workflow LLC" three days after the name was dropped.
  * The real app could only be changed by `clasp push` + `clasp deploy`, and its
    DATA could only change by running buildProductDemo() from the Apps Script
    editor by hand -- `clasp run` is not configured -- so a data fix sat waiting
    on a Monday trigger.
  * It rendered in a cross-origin sandbox iframe, so our own QA gates could not
    read it, synthetic clicks could not reach it, and it could not even be
    screenshotted from this box (script.google.com rewrites /macros/s/ to
    /macros/u/N/s/ and 404s on the wrong account).
  * Apps Script cold start put a spinner in front of the flagship demo.

This version is plain HTML/CSS/JS served from our own domain. It is instant, it
is inspectable by the gates, and -- the part that actually matters -- **its data
is generated in the browser from today's date, so it can never go stale.** There
is no trigger to fire, no sheet to rebuild and no screenshot to recapture.

HOUSE RULES HONOURED HERE
-------------------------
  * "Math from formulas, narrative from templates." Every figure in the written
    summary is computed first and then interpolated. No sentence states a number
    that was not derived from the same series the chart draws.
  * No Math.random(). All variation comes from a deterministic hash keyed on the
    CALENDAR week, so the book is stable across reloads and naturally different
    as real weeks pass. (Position-keyed noise made history visibly mutate.)
  * Zero network requests after load. Same claim the free tools make.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / 'demo' / 'index.html'

START = '<!-- DEMO-APP:START (generated by _brand/build_demo_app.py -- do not edit by hand) -->'
END = '<!-- DEMO-APP:END -->'


APP_CSS = """
/* ---- interactive demo dashboard -------------------------------------- */
.dapp{--d-paper:#fff;--d-tint:#FBFAF3;--d-well:#F4F1E8;--d-ink:#211D14;
  --d-soft:#5C5645;--d-line:#E4DFD1;--d-line2:#D3CBB4;--d-green:#1E7A47;
  --d-red:#B4402F;--d-amber:#8A6A16;--d-bar:#CBC5B1;
  --d-mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
  max-width:1160px;margin:0 auto;border:1px solid var(--d-line);border-radius:14px;
  background:var(--d-paper);box-shadow:0 10px 30px rgba(33,29,20,.10);overflow:hidden;
  display:grid;grid-template-columns:212px 1fr;color:var(--d-ink);
  font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
.dapp *{box-sizing:border-box}

.dnav{background:var(--d-tint);border-right:1px solid var(--d-line);padding:1.1rem .8rem;
  display:flex;flex-direction:column;gap:.15rem;min-width:0}
.dbiz{font-size:1.06rem;font-weight:700;letter-spacing:-.015em;line-height:1.25;
  margin:0 .35rem .3rem;text-wrap:balance}
.dlive{display:flex;align-items:center;gap:.4rem;margin:0 .35rem 1rem;
  font-family:var(--d-mono);font-size:.62rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-green);font-weight:600}
.dlive i{width:6px;height:6px;border-radius:50%;background:var(--d-green);
  display:inline-block;flex:none;animation:dpulse 2.4s ease-in-out infinite}
@keyframes dpulse{0%,100%{opacity:1}50%{opacity:.35}}
.dtab{display:flex;align-items:center;gap:.55rem;width:100%;text-align:left;
  background:none;border:0;border-radius:9px;padding:.5rem .6rem;cursor:pointer;
  font:inherit;font-size:.9rem;color:var(--d-soft);position:relative}
.dtab:hover{background:var(--d-well);color:var(--d-ink)}
.dtab[aria-selected="true"]{background:var(--d-paper);color:var(--d-ink);font-weight:600;
  box-shadow:0 1px 3px rgba(33,29,20,.10);border:1px solid var(--d-line)}
.dtab:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}
.dtab .dic{width:15px;height:15px;flex:none;opacity:.75}
.dtab .dbadge{margin-left:auto;font-family:var(--d-mono);font-size:.62rem;font-weight:700;
  background:var(--d-red);color:#fff;border-radius:999px;padding:.05rem .38rem;line-height:1.5}
.dnav-foot{margin-top:auto;padding:.9rem .35rem 0;border-top:1px solid var(--d-line);
  font-family:var(--d-mono);font-size:.6rem;letter-spacing:.07em;text-transform:uppercase;
  color:var(--d-soft);line-height:1.7}
.dnav-foot a{color:inherit}

.dmain{min-width:0;display:flex;flex-direction:column}
.dtop{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;
  padding:.7rem 1.1rem;border-bottom:1px solid var(--d-line);background:var(--d-tint)}
.ddots{display:flex;gap:.3rem;margin-right:.2rem}
.ddots i{width:8px;height:8px;border-radius:50%;background:var(--d-line2);display:block}
.dcrumb{font-family:var(--d-mono);font-size:.66rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-soft);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}
.dchips{margin-left:auto;display:flex;gap:.35rem;flex-wrap:wrap}
.dchip{font-family:var(--d-mono);font-size:.62rem;letter-spacing:.06em;text-transform:uppercase;
  border:1px solid var(--d-line2);border-radius:999px;padding:.2rem .55rem;color:var(--d-soft);
  background:var(--d-paper);white-space:nowrap}
.dchip.ok{border-color:var(--d-green);color:var(--d-green)}
.dchip.warn{border-color:var(--d-amber);color:var(--d-amber);font-weight:700}

.dbody{padding:1.15rem 1.1rem 1.3rem;min-width:0}
.dh{margin:0 0 .1rem;font-size:1.5rem;letter-spacing:-.02em;font-weight:700}
.dhsub{margin:0 0 1rem;color:var(--d-soft);font-size:.87rem}

.dsum{border:1px solid var(--d-line);border-left:3px solid var(--d-green);
  border-radius:10px;background:var(--d-tint);padding:.85rem .95rem;margin:0 0 1.05rem}
.dsum-h{display:flex;align-items:center;gap:.4rem;margin:0 0 .35rem;
  font-family:var(--d-mono);font-size:.6rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--d-green);font-weight:700}
.dsum p{margin:0;font-size:.97rem;line-height:1.62;text-wrap:pretty}
.dsum b{font-weight:700}

.dkpis{display:grid;grid-template-columns:repeat(4,1fr);gap:.6rem;margin:0 0 1.05rem}
.dkpi{border:1px solid var(--d-line);border-radius:10px;padding:.7rem .8rem;background:var(--d-paper);
  min-width:0;text-align:left;font:inherit;cursor:pointer;position:relative}
.dkpi:hover{border-color:var(--d-line2);background:var(--d-tint)}
.dkpi:focus-visible{outline:2px solid var(--d-green);outline-offset:2px}
.dkpi .dk-l{font-family:var(--d-mono);font-size:.6rem;letter-spacing:.09em;text-transform:uppercase;
  color:var(--d-soft);display:block;margin-bottom:.28rem;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}
.dkpi .dk-v{font-size:1.42rem;font-weight:800;letter-spacing:-.025em;
  font-variant-numeric:tabular-nums;display:block;line-height:1.12}
.dkpi .dk-d{font-family:var(--d-mono);font-size:.63rem;margin-top:.24rem;display:block;
  color:var(--d-soft)}
.dk-d.pos{color:var(--d-green)}
.dk-d.neg{color:var(--d-red)}

.dgrid{display:grid;grid-template-columns:1.35fr 1fr;gap:.7rem}
.dpanel{border:1px solid var(--d-line);border-radius:10px;background:var(--d-paper);
  padding:.8rem .9rem;min-width:0}
.dph{display:flex;align-items:baseline;gap:.5rem;margin:0 0 .7rem;
  font-family:var(--d-mono);font-size:.62rem;letter-spacing:.09em;text-transform:uppercase;
  color:var(--d-soft)}
.dph b{color:var(--d-ink);font-weight:700}
.dph .dlink{margin-left:auto;color:var(--d-green);cursor:pointer;background:none;border:0;
  font:inherit;font-family:var(--d-mono);font-size:.62rem;letter-spacing:.06em;
  text-transform:uppercase;padding:0}
.dph .dlink:hover{text-decoration:underline}

.dchartwrap{width:100%;min-width:0}
.dchart{width:100%;display:block}
.dchart .cb{fill:var(--d-bar);transition:fill .15s ease}
.dchart .cb.hi{fill:var(--d-ink)}
.dchart .cb.best{fill:var(--d-green)}
.dchart .cb:hover{fill:var(--d-ink)}
.dchart .cg{stroke:var(--d-line);stroke-width:1}
/* Label strip lives in HTML, not in the SVG -- see the comment on chart(). */
.dclabels{display:flex;gap:1.4%;margin-top:.4rem}
.dclabels .dcl{flex:1 1 0;min-width:0;text-align:center;font-family:var(--d-mono);
  font-size:.6rem;color:var(--d-soft);white-space:nowrap;overflow:hidden}
.dclabels .dcl.cur{color:var(--d-ink);font-weight:700}

.drow{display:flex;align-items:flex-start;gap:.6rem;padding:.5rem 0;
  border-bottom:1px solid var(--d-line)}
.drow:last-child{border-bottom:0;padding-bottom:0}
.drow .dr-m{min-width:0;flex:1}
.drow .dr-n{font-weight:600;font-size:.9rem;display:block;white-space:nowrap;
  overflow:hidden;text-overflow:ellipsis}
.drow .dr-s{font-family:var(--d-mono);font-size:.62rem;letter-spacing:.045em;
  text-transform:uppercase;color:var(--d-soft);display:block;margin-top:.1rem}
.drow .dr-s.late{color:var(--d-red)}
.drow .dr-a{font-family:var(--d-mono);font-size:.88rem;font-weight:700;
  font-variant-numeric:tabular-nums;white-space:nowrap}
.dpill{background:#FDF3D4;border:1px solid #E6D08A;color:#6B5310;border-radius:5px;
  padding:.05rem .34rem;font-size:.72rem}

.dstats{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin:0 0 .85rem}
.dstat{border:1px solid var(--d-line);border-radius:9px;padding:.55rem .65rem;
  background:var(--d-tint);min-width:0}
.dstat .ds-v{font-size:1.02rem;font-weight:800;font-variant-numeric:tabular-nums;
  letter-spacing:-.015em;display:block}
.dstat .ds-l{font-family:var(--d-mono);font-size:.57rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--d-soft);display:block;margin-top:.15rem}
.ds-v.pos{color:var(--d-green)}
.ds-v.neg{color:var(--d-red)}

.dage{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin:0 0 .9rem}
.dagec{border:1px solid var(--d-line);border-radius:9px;padding:.6rem .7rem;background:var(--d-paper)}
.dagec .da-l{font-family:var(--d-mono);font-size:.58rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--d-soft)}
.dagec .da-v{font-size:1.06rem;font-weight:800;font-variant-numeric:tabular-nums;
  margin:.18rem 0 .38rem;letter-spacing:-.015em}
.dagec .da-t{height:6px;border-radius:999px;background:var(--d-well);overflow:hidden}
.dagec .da-f{height:100%;border-radius:999px;background:var(--d-green)}
.dagec.b2 .da-f{background:#C79A2E}
.dagec.b3 .da-f{background:#C2701F}
.dagec.b4 .da-f{background:var(--d-red)}

.dnote{margin:.85rem 0 0;font-size:.85rem;color:var(--d-soft);text-wrap:pretty}
.dnote b{color:var(--d-ink)}

.drep{display:flex;align-items:center;gap:.7rem;padding:.55rem 0;
  border-bottom:1px solid var(--d-line)}
.drep:last-child{border-bottom:0}
.drep .dp-d{font-family:var(--d-mono);font-size:.68rem;color:var(--d-soft);
  white-space:nowrap;min-width:5.4rem}
.drep .dp-t{font-size:.89rem;min-width:0;flex:1}
.drep .dp-s{font-family:var(--d-mono);font-size:.6rem;letter-spacing:.06em;
  text-transform:uppercase;color:var(--d-green);white-space:nowrap}

.dfoot{margin-top:auto;padding:.6rem 1.1rem;border-top:1px solid var(--d-line);
  background:var(--d-tint);font-family:var(--d-mono);font-size:.6rem;letter-spacing:.07em;
  text-transform:uppercase;color:var(--d-soft);display:flex;gap:.6rem;flex-wrap:wrap;
  align-items:center}
.dfoot a{color:inherit}
.dfoot .dsp{margin-left:auto}

@media (max-width:860px){
  .dapp{grid-template-columns:1fr}
  .dnav{flex-direction:row;align-items:center;gap:.3rem;overflow-x:auto;
    border-right:0;border-bottom:1px solid var(--d-line);padding:.55rem .6rem;
    -webkit-overflow-scrolling:touch;scrollbar-width:none}
  .dnav::-webkit-scrollbar{display:none}
  .dbiz,.dlive,.dnav-foot{display:none}
  .dtab{width:auto;white-space:nowrap;flex:none;padding:.42rem .7rem;font-size:.84rem}
  .dgrid{grid-template-columns:1fr}
  .dkpis{grid-template-columns:repeat(2,1fr)}
  .dstats{grid-template-columns:repeat(2,1fr)}
  .dage{grid-template-columns:repeat(2,1fr)}
  .dbody{padding:.95rem .8rem 1.1rem}
  .dh{font-size:1.28rem}
}
@media (max-width:430px){
  .dkpi .dk-v{font-size:1.22rem}
  .dtop{padding:.55rem .7rem}
  .dchips{width:100%;margin-left:0}
}
@media (prefers-reduced-motion:reduce){
  .dlive i{animation:none}
  .dchart .cb,.dchart .cv{transition:none}
}
"""


APP_HTML = """
<div class="frame-wrap">

  <div class="dapp" id="dapp">
    <nav class="dnav" role="tablist" aria-label="Dashboard sections">
      <p class="dbiz" id="d-biz">Gator Shine Exterior Cleaning</p>
      <p class="dlive"><i aria-hidden="true"></i>Live &middot; self-updating</p>

      <button class="dtab" id="tab-dashboard" role="tab" aria-selected="true"
              aria-controls="view-dashboard" data-view="dashboard" type="button">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <rect x="1.5" y="1.5" width="5.4" height="5.4" rx="1"/><rect x="9.1" y="1.5" width="5.4" height="5.4" rx="1"/>
          <rect x="1.5" y="9.1" width="5.4" height="5.4" rx="1"/><rect x="9.1" y="9.1" width="5.4" height="5.4" rx="1"/>
        </svg>Dashboard</button>

      <button class="dtab" id="tab-revenue" role="tab" aria-selected="false"
              aria-controls="view-revenue" data-view="revenue" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M1.6 11.6 5.6 6.9l3 2.6 4.9-6"/><path d="M10.6 3.5h3.4v3.4"/>
        </svg>Revenue</button>

      <button class="dtab" id="tab-receivables" role="tab" aria-selected="false"
              aria-controls="view-receivables" data-view="receivables" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M8 1.4v13.2"/><path d="M11.2 4.2H6.5a2 2 0 0 0 0 4h3a2 2 0 0 1 0 4H4.4"/>
        </svg>Receivables<span class="dbadge" id="d-arbadge">0</span></button>

      <button class="dtab" id="tab-reports" role="tab" aria-selected="false"
              aria-controls="view-reports" data-view="reports" type="button" tabindex="-1">
        <svg class="dic" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6">
          <path d="M3.2 1.7h6.3l3.3 3.3v9.3H3.2z"/><path d="M9.3 1.8v3.4h3.4"/>
        </svg>Reports</button>

      <div class="dnav-foot">built by <a href="/">Automated<br>Workflow</a></div>
    </nav>

    <div class="dmain">
      <div class="dtop">
        <span class="ddots" aria-hidden="true"><i></i><i></i><i></i></span>
        <span class="dcrumb" id="d-crumb">Dashboard &middot; <span id="d-asof"></span></span>
        <span class="dchips">
          <span class="dchip warn">Sample data</span>
          <span class="dchip ok">&#9679; Self-updating</span>
          <span class="dchip" id="d-refreshed">Refreshed</span>
        </span>
      </div>

      <div class="dbody">
        <section id="view-dashboard" role="tabpanel" aria-labelledby="tab-dashboard" tabindex="0">
          <h2 class="dh" id="d-greet">Good morning.</h2>
          <p class="dhsub" id="d-greetsub"></p>

          <div class="dsum">
            <p class="dsum-h">&#10022; AI weekly summary &mdash; written by the dashboard, not by you</p>
            <p id="d-summary"></p>
          </div>

          <div class="dkpis" id="d-kpis"></div>

          <div class="dgrid">
            <div class="dpanel">
              <p class="dph"><b>Revenue</b> &mdash; last 6 weeks
                <button class="dlink" type="button" data-goto="revenue">Full chart &rarr;</button></p>
              <div id="d-minichart"></div>
            </div>
            <div class="dpanel">
              <p class="dph"><b>Receivables</b> &mdash; call first
                <button class="dlink" type="button" data-goto="receivables">All &rarr;</button></p>
              <div id="d-callfirst"></div>
            </div>
          </div>
        </section>

        <section id="view-revenue" role="tabpanel" aria-labelledby="tab-revenue" tabindex="0" hidden>
          <h2 class="dh">Revenue</h2>
          <p class="dhsub">Thirteen weeks of completed work, newest on the right.</p>
          <div class="dstats" id="r-stats"></div>
          <div class="dpanel"><div id="r-chart"></div></div>
          <p class="dnote" id="r-note"></p>
        </section>

        <section id="view-receivables" role="tabpanel" aria-labelledby="tab-receivables" tabindex="0" hidden>
          <h2 class="dh">Receivables</h2>
          <p class="dhsub">What you are owed, oldest first &mdash; because that is the call order.</p>
          <div class="dstats" id="a-stats"></div>
          <div class="dage" id="a-aging"></div>
          <div class="dpanel">
            <p class="dph"><b>Open invoices</b></p>
            <div id="a-list"></div>
          </div>
          <p class="dnote" id="a-note"></p>
        </section>

        <section id="view-reports" role="tabpanel" aria-labelledby="tab-reports" tabindex="0" hidden>
          <h2 class="dh">Reports</h2>
          <p class="dhsub">Every Monday this writes itself and lands in your inbox.</p>
          <div class="dpanel">
            <p class="dph"><b>Archive</b> &mdash; your weekly history</p>
            <div id="p-list"></div>
          </div>
          <p class="dnote">Each one is the summary at the top of the dashboard, captured the morning
          it was written, so you can see what you knew at the time rather than only what is true now.</p>
        </section>
      </div>

      <div class="dfoot">
        <span>Sample data &mdash; yours runs on your numbers</span>
        <span class="dsp" id="d-perf"></span>
      </div>
    </div>
  </div>
</div>

<p class="demo-fallback" style="text-align:center;margin:14px auto 0;max-width:760px;font-size:13px;color:#5C5645">
  That&rsquo;s the real dashboard, running right here &mdash; tap the tabs and the KPI tiles.
  It builds itself from today&rsquo;s date in your browser, which is why it is never out of date.
</p>
"""


APP_JS = r"""
/* aw-demo-app -- the /demo/ dashboard. Client-side, no network after load.
   See _brand/build_demo_app.py for why this replaced the Apps Script embed. */
(function () {
  "use strict";
  var app = document.getElementById('dapp');
  if (!app) { return; }
  var t0 = (window.performance && performance.now) ? performance.now() : 0;

  /* ---------- deterministic variation (no Math.random) ------------------
     Keyed on the CALENDAR week, not on position in the array. A position key
     makes every week's value slide to a new date on each reload, so history
     appears to mutate; a calendar key keeps a given week stable forever and
     lets new weeks differ naturally as time passes. */
  function hash(x){ var s = Math.sin((x + 1) * 12.9898) * 43758.5453; return (s - Math.floor(s)) * 2 - 1; }
  /* Three octaves so neighbouring weeks stay correlated. Independent per-index
     noise reads as a copy-pasted zigzag; a single octave reads as a sine wave. */
  function wobble(k){ return hash(Math.floor(k/4))*0.5 + hash(Math.floor(k/2))*0.32 + hash(k)*0.18; }

  function addDays(d, n){ var x = new Date(d.getTime()); x.setDate(x.getDate() + n); return x; }
  function mondayOf(d){ var x = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    var off = (x.getDay() + 6) % 7; return addDays(x, -off); }
  function epochWeek(d){ return Math.floor(d.getTime() / 604800000); }
  function dayDiff(a, b){ return Math.round((a.getTime() - b.getTime()) / 86400000); }

  var MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function fmtDay(d){ return MON[d.getMonth()] + ' ' + d.getDate(); }
  function fmtLong(d){ return MON[d.getMonth()] + ' ' + d.getDate() + ', ' + d.getFullYear(); }
  function money(n){ return '$' + Math.round(n).toLocaleString('en-US'); }
  function pct(n){ return (n >= 0 ? '+' : '') + n.toFixed(1) + '%'; }

  /* ---------- the book -------------------------------------------------- */
  var TODAY   = new Date();
  var CURMON  = mondayOf(TODAY);
  var BASE    = 11500;   /* target revenue per full week (~$44-49k/mo) */
  var AMP     = 3400;    /* swing. At 1800 the octave blend regressed to the mean and every
                            bar came out the same height -- the chart looked broken. */
  var WEEKS   = 18;

  /* Gentle upward drift across the window (~+11% oldest to newest) on top of the
     wobble. Without it the hash alone decides the shape, and for many starting
     weeks that is a steadily FALLING book -- an odd thing for a sample business
     to model, and it made "0 of 6 weeks above average" the headline stat. This
     is invented data either way and the panel is labelled "Sample data"; the
     choice is only whether the invented business is plausible. Growth stays
     small enough that the week-to-week lumpiness still dominates, because a
     smooth up-and-to-the-right line is the thing nobody believes. */
  var GROWTH = 0.45;

  var weeks = [];
  for (var w = WEEKS - 1; w >= 0; w--) {
    var start = addDays(CURMON, -7 * w);
    var age = (WEEKS - 1 - w) / (WEEKS - 1);          /* 0 = oldest, 1 = newest */
    var trend = 1 + GROWTH * (age - 0.5);
    var target = BASE * trend + AMP * wobble(epochWeek(start));
    /* The current week is only as far along as today, so it is not comparable to
       a finished week. Pro-rating it stops the newest bar reading as a crash. */
    var isCur = (w === 0);
    var elapsed = isCur ? Math.min(7, Math.max(1, dayDiff(TODAY, start) + 1)) : 7;
    var frac = elapsed / 7;
    weeks.push({ start: start, label: fmtDay(start), value: Math.max(600, Math.round(target * frac)),
                 full: Math.round(target),
                 /* days actually elapsed in this week -- the divisor for any
                    per-day figure. Dividing a pro-rated week by 7 under-counts
                    the days that did happen. */
                 days: elapsed,
                 partial: isCur && elapsed < 7 });
  }

  var CUSTOMERS = [
    'Hogtown Brewing','Sweetwater Vet Clinic','Celebration Pointe Realty','Haile Plantation HOA',
    'Depot Park Cafe','Archer Road Dental','Tioga Town Homes','Duckpond B&B','Micanopy Vintage Co.'
  ];

  /* Open invoices. Ages are fixed offsets so the aging buckets are always
     populated the same way; amounts vary deterministically by index. */
  var AGES = [96, 66, 47, 31, 12, 6];
  var receivables = AGES.map(function (age, i) {
    var amt = 900 + Math.round((1 + hash(i * 17)) * 950) * 2;
    return { customer: CUSTOMERS[i % CUSTOMERS.length], days: age, amount: amt,
             due: addDays(TODAY, -age) };
  }).sort(function (a, b) { return b.days - a.days; });

  var arTotal = receivables.reduce(function (s, r) { return s + r.amount; }, 0);
  var overdue = receivables.filter(function (r) { return r.days > 30; });
  var overdueTotal = overdue.reduce(function (s, r) { return s + r.amount; }, 0);

  /* Month-to-date from the weekly series: only the part of each week that falls
     inside the current calendar month. Computed, never typed. */
  /* Sum the days of the weekly series that fall inside a given calendar month,
     up to a day-of-month limit. perDay uses wk.days, not 7, so a pro-rated
     current week is not double-discounted. */
  function monthSum(monthRef, dayLimit){
    var m = monthRef.getMonth(), y = monthRef.getFullYear(), sum = 0;
    weeks.forEach(function (wk) {
      var perDay = wk.value / wk.days;
      for (var d = 0; d < wk.days; d++) {
        var day = addDays(wk.start, d);
        if (day.getMonth() === m && day.getFullYear() === y && day.getDate() <= dayLimit) { sum += perDay; }
      }
    });
    return Math.round(sum);
  }
  function monthToDate(){ return monthSum(TODAY, TODAY.getDate()); }
  /* Same day-of-month cut-off in the prior month, so it is a like-for-like
     comparison rather than a part-month against a whole one. */
  function priorMonthSame(){
    return monthSum(new Date(TODAY.getFullYear(), TODAY.getMonth() - 1, 1), TODAY.getDate());
  }

  var mtd = monthToDate();
  var pmtd = priorMonthSame();
  var mtdDelta = pmtd > 0 ? ((mtd - pmtd) / pmtd) * 100 : 0;
  /* "Never invoiced" is the thing this whole product is pointed at: finished work
     that no one billed. Derived from the book so it moves with it. */
  var neverInvoiced = Math.round((weeks[weeks.length - 2].value + weeks[weeks.length - 3].value) * 0.17);
  var spend = 226 + Math.round((1 + hash(epochWeek(CURMON))) * 140);
  var netCash = mtd - spend;
  var activeCustomers = CUSTOMERS.length + 3;

  /* ---------- rendering helpers ---------------------------------------- */
  function el(id){ return document.getElementById(id); }
  function esc(s){ return String(s).replace(/[&<>"]/g, function (c) {
    return ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' })[c]; }); }

  /* Bar chart: SVG for the bars, HTML for every piece of text.
     WHY THE TEXT IS NOT IN THE SVG. The bars want preserveAspectRatio="none" so
     they stretch to whatever width the panel is without a resize listener. That
     scales the coordinate system non-uniformly -- and any <text> inside stretches
     with it, so at a ~4x horizontal scale the axis labels rendered enormous and
     overlapping. Text in a non-uniformly scaled SVG cannot be made to behave;
     the fix is to keep text out of it. Labels and values are a normal HTML flex
     row under the chart, sharing the same column widths. */
  function chart(rows, opts){
    opts = opts || {};
    var n = rows.length, W = 100, H = opts.h || 34, gap = 1.4;
    var bw = (W - gap * (n - 1)) / n;
    var max = 0, bestI = 0;
    rows.forEach(function (r, i) { if (r.value > max) { max = r.value; bestI = i; } });
    if (max <= 0) { max = 1; }

    var svg = ['<svg class="dchart" viewBox="0 0 ' + W + ' ' + H +
               '" preserveAspectRatio="none" role="img" aria-label="' +
               esc(opts.label || 'Revenue by week') + '" style="height:' + (opts.px || 120) + 'px">'];
    [0.25, 0.5, 0.75].forEach(function (g) {
      var y = (H - H * g).toFixed(2);
      svg.push('<line class="cg" x1="0" y1="' + y + '" x2="' + W + '" y2="' + y +
               '" vector-effect="non-scaling-stroke"/>');
    });
    rows.forEach(function (r, i) {
      var h = Math.max(0.8, (r.value / max) * H);
      var x = i * (bw + gap), y = H - h;
      var cls = 'cb';
      if (i === bestI) { cls += ' best'; }
      if (i === n - 1) { cls += ' hi'; }
      svg.push('<rect class="' + cls + '" x="' + x.toFixed(2) + '" y="' + y.toFixed(2) +
               '" width="' + bw.toFixed(2) + '" height="' + h.toFixed(2) + '">' +
               '<title>' + esc(r.label) + ' · ' + money(r.value) +
               (r.partial ? ' (week in progress)' : '') + '</title></rect>');
    });
    svg.push('</svg>');

    /* Label strip. Every other label is dropped on dense charts so they never
       collide -- the tooltip still carries the exact figure for each bar. */
    var labs = rows.map(function (r, i) {
      var skip = (n > 8 && (i % 2 === 1));
      return '<span class="dcl' + (i === n - 1 ? ' cur' : '') + '">' +
             (skip ? '' : esc(r.label)) + '</span>';
    }).join('');

    return '<div class="dchartwrap">' + svg.join('') +
           '<div class="dclabels" aria-hidden="true">' + labs + '</div></div>';
  }

  function rowsHTML(items){
    return items.map(function (r) {
      var late = r.days > 30;
      var note = late ? (r.days + 'd overdue · ' + (r.days > 90 ? 'oldest open — call first'
                        : r.days > 60 ? 'crossed 60 days' : 'due ' + fmtDay(r.due)))
                      : ('due ' + fmtDay(addDays(r.due, 30)));
      return '<div class="drow"><span class="dr-m"><span class="dr-n">' + esc(r.customer) + '</span>' +
             '<span class="dr-s' + (late ? ' late' : '') + '">' + esc(note) + '</span></span>' +
             '<span class="dr-a">' + (r.days > 90 ? '<span class="dpill">' + money(r.amount) + '</span>'
                                                  : money(r.amount)) + '</span></div>';
    }).join('');
  }

  function stat(v, l, tone){
    return '<div class="dstat"><span class="ds-v' + (tone ? ' ' + tone : '') + '">' + v +
           '</span><span class="ds-l">' + esc(l) + '</span></div>';
  }

  /* ---------- the written summary --------------------------------------
     HOUSE RULE: math from formulas, narrative from a template. Every number
     below is computed above and interpolated here. Nothing is estimated in
     prose, because a sentence that quietly disagrees with the chart above it
     is the exact failure this product exists to catch. */
  function summary(){
    var worst = receivables[0];
    var s = 'Revenue this month is <b>' + money(mtd) + '</b> (' + pct(mtdDelta) +
            ' vs the same point last month). You are owed <b>' + money(arTotal) + '</b>';
    if (worst) {
      s += '; call <b>' + esc(worst.customer) + '</b> first — ' + money(worst.amount) +
           ' is ' + worst.days + ' days past due';
    }
    s += '. Finished-but-never-invoiced work totals <b>' + money(neverInvoiced) +
         '</b> — invoice it this week. Spending is ' + money(spend) +
         ' this month, leaving <b>' + money(netCash) + '</b> net cash flow.';
    return s;
  }

  /* ---------- views ----------------------------------------------------- */
  function renderDashboard(){
    var h = TODAY.getHours();
    el('d-greet').textContent = h < 12 ? 'Good morning.' : (h < 18 ? 'Good afternoon.' : 'Good evening.');
    el('d-greetsub').textContent = 'Here is where the business stands as of ' + fmtLong(TODAY) + '.';
    el('d-summary').innerHTML = summary();

    var kpis = [
      { l: 'Monthly revenue', v: money(mtd), d: pct(mtdDelta) + ' vs prior MTD', t: mtdDelta >= 0 ? 'pos' : 'neg', go: 'revenue' },
      { l: 'Outstanding AR',  v: money(arTotal), d: overdue.length + ' invoices past due', t: 'neg', go: 'receivables' },
      { l: 'Net cash flow',   v: money(netCash), d: money(spend) + ' spent this month', t: netCash >= 0 ? 'pos' : 'neg', go: 'revenue' },
      { l: 'Active customers',v: String(activeCustomers), d: 'across 3 crews', t: '', go: 'receivables' }
    ];
    el('d-kpis').innerHTML = kpis.map(function (k) {
      return '<button class="dkpi" type="button" data-goto="' + k.go + '">' +
             '<span class="dk-l">' + esc(k.l) + '</span>' +
             '<span class="dk-v">' + k.v + '</span>' +
             '<span class="dk-d' + (k.t ? ' ' + k.t : '') + '">' + esc(k.d) + '</span></button>';
    }).join('');

    el('d-minichart').innerHTML = chart(weeks.slice(-6), { h: 30, px: 132, label: 'Revenue, last six weeks' });
    el('d-callfirst').innerHTML = rowsHTML(receivables.slice(0, 3));
  }

  function renderRevenue(){
    var rows = weeks.slice(-13);

    /* EVERY PERIOD STAT USES COMPLETE WEEKS ONLY.
       The newest week is only as far along as today, so including it drags an
       average down and turns an ordinary Tuesday into "revenue is falling".
       That is a measurement artifact -- the number moves without the business
       moving -- and shipping one inside a dashboard that sells honest
       measurement would be the exact thing this product exists to catch. The
       partial week still appears in the chart, where it is visibly the current
       week, because hiding it would be its own kind of lie. */
    var done = rows.filter(function (r) { return !r.partial; });
    var vals = done.map(function (r) { return r.value; });
    if (!vals.length) { vals = rows.map(function (r) { return r.value; }); done = rows; }

    var best = Math.max.apply(null, vals);
    var bestRow = done[vals.indexOf(best)];
    var avg = vals.reduce(function (a, b) { return a + b; }, 0) / vals.length;
    var half = Math.floor(vals.length / 2);
    var recent = vals.slice(half).reduce(function (a, b) { return a + b; }, 0);
    var prior  = vals.slice(0, half).reduce(function (a, b) { return a + b; }, 0);
    var above  = vals.slice(half).filter(function (v) { return v > avg; }).length;
    var delta  = recent - prior;

    el('r-stats').innerHTML =
      stat(money(best), 'Best week · ' + bestRow.label) +
      stat(money(avg), vals.length + '-wk avg / wk') +
      stat((delta >= 0 ? '+' : '') + money(delta), 'vs prior ' + half + ' wks',
           delta >= 0 ? 'pos' : 'neg') +
      stat(above + ' of ' + (vals.length - half), 'Weeks above avg');
    el('r-chart').innerHTML = chart(rows, { h: 40, px: 168, label: 'Revenue, last thirteen weeks' });
    el('r-note').innerHTML = 'Best week was <b>' + bestRow.label + '</b> at ' + money(best) +
      '. The newest bar is the week in progress, so it is short by design rather than a downturn — ' +
      '<b>every figure above is calculated on completed weeks only</b>, because an average that ' +
      'quietly includes a half-finished week drops every Monday and recovers by Friday, and you ' +
      'would spend months reacting to the calendar instead of the business.';
  }

  function renderReceivables(){
    var buckets = [
      { l: '0–30',  v: receivables.filter(function(r){ return r.days <= 30; }) },
      { l: '31–60', v: receivables.filter(function(r){ return r.days > 30 && r.days <= 60; }) },
      { l: '61–90', v: receivables.filter(function(r){ return r.days > 60 && r.days <= 90; }) },
      { l: '90+',        v: receivables.filter(function(r){ return r.days > 90; }) }
    ].map(function (b) { return { l: b.l, total: b.v.reduce(function(s,r){ return s+r.amount; }, 0) }; });
    var mx = Math.max.apply(null, buckets.map(function (b) { return b.total; })) || 1;
    var worst = receivables[0];

    el('a-stats').innerHTML =
      stat(money(arTotal), 'Total outstanding') +
      stat(money(overdueTotal), 'Overdue', 'neg') +
      stat(String(overdue.length), 'Invoices past due') +
      stat(worst ? worst.days + 'd' : '—', 'Oldest overdue');
    el('a-aging').innerHTML = buckets.map(function (b, i) {
      return '<div class="dagec b' + (i + 1) + '"><span class="da-l">' + b.l + ' days</span>' +
             '<span class="da-v">' + money(b.total) + '</span>' +
             '<span class="da-t"><span class="da-f" style="width:' +
             Math.max(3, Math.round(b.total / mx * 100)) + '%"></span></span></div>';
    }).join('');
    el('a-list').innerHTML = rowsHTML(receivables);
    el('a-note').innerHTML = 'Of <b>' + money(arTotal) + '</b> outstanding, <b>' + money(overdueTotal) +
      '</b> is past 30 days' + (worst ? '. Start with <b>' + esc(worst.customer) + '</b> (' +
      money(worst.amount) + ', ' + worst.days + 'd late)' : '') +
      '. The chase emails draft themselves — and then wait for you to press send.';
  }

  function renderReports(){
    var out = [];
    for (var i = 0; i < 8; i++) {
      var d = addDays(CURMON, -7 * i);
      out.push('<div class="drep"><span class="dp-d">' + fmtDay(d) +
               '</span><span class="dp-t">Weekly summary — revenue, receivables and what to chase' +
               '</span><span class="dp-s">' + (i === 0 ? 'This week' : 'Sent') + '</span></div>');
    }
    el('p-list').innerHTML = out.join('');
  }

  /* ---------- tabs ------------------------------------------------------ */
  var VIEWS = ['dashboard','revenue','receivables','reports'];
  var LABEL = { dashboard:'Dashboard', revenue:'Revenue', receivables:'Receivables', reports:'Reports' };
  var rendered = {};

  function show(name){
    if (VIEWS.indexOf(name) < 0) { name = 'dashboard'; }
    VIEWS.forEach(function (v) {
      var panel = el('view-' + v), tab = el('tab-' + v), on = (v === name);
      if (panel) { panel.hidden = !on; }
      if (tab) { tab.setAttribute('aria-selected', on ? 'true' : 'false');
                 tab.tabIndex = on ? 0 : -1; }
    });
    if (!rendered[name]) {
      if (name === 'revenue') { renderRevenue(); }
      else if (name === 'receivables') { renderReceivables(); }
      else if (name === 'reports') { renderReports(); }
      rendered[name] = true;
    }
    el('d-crumb').innerHTML = LABEL[name] + ' &middot; <span id="d-asof">' + fmtLong(TODAY) + '</span>';
  }

  app.addEventListener('click', function (ev) {
    var t = ev.target.closest('[data-view],[data-goto]');
    if (!t || !app.contains(t)) { return; }
    var name = t.getAttribute('data-view') || t.getAttribute('data-goto');
    show(name);
    if (t.getAttribute('data-goto')) {
      var tab = el('tab-' + name);
      if (tab) { try { tab.focus(); } catch (e) {} }
    }
  });

  /* Arrow-key movement between tabs -- expected of role="tablist", and the
     thing screen-reader users notice is missing. */
  app.addEventListener('keydown', function (ev) {
    var t = ev.target;
    if (!t || !t.classList || !t.classList.contains('dtab')) { return; }
    var i = VIEWS.indexOf(t.getAttribute('data-view'));
    if (i < 0) { return; }
    var next = null;
    if (ev.key === 'ArrowRight' || ev.key === 'ArrowDown') { next = VIEWS[(i + 1) % VIEWS.length]; }
    else if (ev.key === 'ArrowLeft' || ev.key === 'ArrowUp') { next = VIEWS[(i - 1 + VIEWS.length) % VIEWS.length]; }
    else if (ev.key === 'Home') { next = VIEWS[0]; }
    else if (ev.key === 'End') { next = VIEWS[VIEWS.length - 1]; }
    if (!next) { return; }
    ev.preventDefault();
    show(next);
    var tab = el('tab-' + next);
    if (tab) { try { tab.focus(); } catch (e) {} }
  });

  /* ---------- boot ------------------------------------------------------ */
  el('d-arbadge').textContent = String(overdue.length);
  el('d-refreshed').textContent = 'Built ' +
    TODAY.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  renderDashboard();
  show('dashboard');

  if (t0) {
    var ms = Math.max(1, Math.round(performance.now() - t0));
    el('d-perf').textContent = 'Built in ' + ms + 'ms · 0 requests';
  } else {
    el('d-perf').textContent = '0 requests after load';
  }
})();
"""


def main() -> None:
    s = PAGE.read_text(encoding='utf-8')

    block = (START + '\n<style>' + APP_CSS + '</style>\n'
             + APP_HTML + '\n<script>' + APP_JS + '</script>\n' + END)

    if START in s:
        # Idempotent path: swap whatever is between the markers. Re-running with
        # an unchanged template legitimately produces a byte-identical file, so
        # "no change" is a pass here, not a failure -- only a missing END marker
        # (i.e. nothing actually matched) is worth stopping for.
        s, n = re.subn(re.escape(START) + r'.*?' + re.escape(END), lambda _m: block, s, flags=re.S)
        if n != 1:
            raise SystemExit('expected exactly one marker block, matched %d' % n)
    else:
        # First run: take out the screenshot + its caption and drop the app in.
        m = re.search(r'  <div class="frame-wrap">.*?</div>\s*\n\s*<p class="demo-fallback".*?</p>\n',
                      s, flags=re.S)
        if not m:
            raise SystemExit('could not find the frame-wrap/demo-fallback block to replace')
        s = s[:m.start()] + block + '\n' + s[m.end():]

    PAGE.write_text(s, encoding='utf-8')
    print('wrote %s (%d bytes)' % (PAGE, len(s)))


if __name__ == '__main__':
    main()
