#!/usr/bin/env python3
"""Build /proof/ai/ -- the public record of our own AI runs.

custody's `report` command emits a standalone page: correct, but a bare
document with no canonical link, no viewport, no contact details and no site
chrome. That is right for the tool -- it is handed to a board, not published --
and wrong for a page on this site, which is why the SEO gate rejected it with
six defects the first time it was generated.

So the split is: custody stays generic and owns the CONTENT, this builder owns
the SHELL. The alternative -- teaching custody about our canonical URLs and
phone number -- would put one customer's site inside a tool other people are
meant to use.

The content is regenerated from the real ledger on every build, with
--redact, because this page is published rather than handed to the owner of
the data: a filename names a customer before anyone opens the file.

This page is deliberately small at launch and says so itself. Its worth is
that it accumulates, and that nothing can be quietly removed from it later --
the receipts behind it are hash-chained and the head is anchored at /proof/.
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

from toolkit import PLAIN_CSS

ROOT = pathlib.Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / 'spreadsheet-cleanup-service' / 'index.html'
OUT_DIR = ROOT / 'proof' / 'ai'
CUSTODY = pathlib.Path.home() / 'claude' / 'dev' / 'custody' / 'custody.py'

TITLE = 'What Our AI Did — A Public, Signed Record of Every Run'
DESC = ('Every AI run we make, recorded as a signed receipt: which model, what it could read, '
        'who approved it, and whether it later turned out wrong.')
CANON = 'https://automatedworkflowllc.com/proof/ai/'

INTRO = """
<p class="ai-intro">Every AI vendor asks to be trusted. This is the record that makes the
question answerable instead: what our own AI did, taken from the same hash-chained ledger
that <a href="/proof/">/proof/</a> anchors publicly, generated by
<a href="https://github.com/automatedworkflowllc-design/custody">custody</a> rather than
written by hand.</p>
<p class="ai-intro"><b>It is small right now, and that is the honest state of it.</b> It began
on 2026-08-08. The point of a record like this is not how impressive it looks on day one &mdash;
it is that it accumulates, that the uncomfortable rows are in it, and that nothing can be
removed later without the chain showing it.</p>
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    tmp = OUT_DIR / '_custody_raw.html'

    # exit 1 means "something here needs a person" (an unapproved or wrong run),
    # which is the normal state of an honest record -- not a build failure.
    proc = subprocess.run(
        [sys.executable, str(CUSTODY), 'report', '--out', str(tmp),
         '--org', 'Automated Workflow LLC', '--redact'],
        capture_output=True, text=True)
    if proc.returncode not in (0, 1) or not tmp.exists():
        raise SystemExit(f'refusing to build /proof/ai/: custody report failed\n{proc.stderr}')

    raw = tmp.read_text(encoding='utf-8')
    style = re.search(r'<style>(.*?)</style>', raw, re.S)
    body = raw[style.end():] if style else raw
    tmp.unlink()

    # A published page must not name the files a run read. custody was asked to
    # redact, but verify rather than trust the flag: this is the one page where
    # being wrong is public and permanent.
    for leak in ('hisbo', 'AppData', 'C:\\Users', 'C:/Users'):
        if leak in body:
            raise SystemExit(f'refusing to build /proof/ai/: {leak!r} reached the page')

    s = TEMPLATE.read_text(encoding='utf-8')
    head = s[:s.index('</header>') + len('</header>')]
    footer = s[s.index('<footer'):s.index('</footer>') + len('</footer>')]

    head = re.sub(r'<title>.*?</title>', f'<title>{TITLE}</title>', head, flags=re.S)
    head = re.sub(r'(<meta name="description" content=").*?(">)', rf'\g<1>{DESC}\g<2>', head)
    head = re.sub(r'(<link rel="canonical" href=").*?(">)', rf'\g<1>{CANON}\g<2>', head)
    head = re.sub(r'(<meta property="og:title" content=").*?(">)', rf'\g<1>{TITLE}\g<2>', head)
    head = re.sub(r'(<meta property="og:description" content=").*?(">)', rf'\g<1>{DESC}\g<2>', head)
    head = re.sub(r'(<meta property="og:url" content=").*?(">)', rf'\g<1>{CANON}\g<2>', head)

    scoped = (style.group(1) if style else '').replace('body{', '.ai-report{')
    page_css = (scoped + '\n.ai-report{max-width:none;padding:0;margin:0;background:none}'
                         '\n.ai-intro{color:var(--ink-soft);max-width:42rem;margin:.2rem 0 1rem}')
    head = head.replace('</head>', f'<style>{page_css}{PLAIN_CSS}</style>\n</head>')

    main_html = (f'<main id="main" class="wrap" style="padding-top:2.2rem;'
                 f'padding-bottom:3rem;max-width:52rem">{INTRO}'
                 f'<div class="ai-report">{body}</div></main>')

    page = head + main_html + footer + '\n</body>\n</html>\n'
    (OUT_DIR / 'index.html').write_text(page, encoding='utf-8')
    # The head is copied from the shared template, which carries the managed analytics
    # block -- so a regeneration reproduces it at the TEMPLATE's position while
    # apply_analytics puts it just before </head>. Those two positions differ, so the
    # pre-push freshness gate saw an endless diff. Re-applying here settles it.
    import subprocess as _sp, sys as _sys, os as _os
    _sp.run([_sys.executable, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
             'apply_analytics.py')], capture_output=True, check=True)
    print(f'wrote {OUT_DIR / "index.html"} ({len(page)} bytes)')


if __name__ == '__main__':
    main()
