#!/usr/bin/env python3
"""Build /automation-monitoring/ -- the recurring rung, sold on a true story.

The service ladder had one-off rungs ($300 cleanup, $650 dashboard) and
nothing that renews. Monitoring renews. This page sells the standing guard:
we watch your automations, you get a weekly evidence report, and when
something goes quiet you hear it from us before it costs you.

The pitch is a story that actually happened, on our own machine, the day this
page was built: a scheduled digest fired on time, wrote its file, passed every
freshness check -- and was serving Friday's data under Monday's timestamp.
The embedded report below the fold is THAT catch, generated by the real
watchpost engine (dev/watchpost), with paths generalized so we are not
publishing our machine's internals. Nothing on this page is a mockup.

No JavaScript: this page makes no claims it has to compute.
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / 'spreadsheet-cleanup-service' / 'index.html'
DEMO_REPORT = pathlib.Path(r'C:\Users\hisbo\claude\dev\watchpost\demo-report.html')
OUT_DIR = ROOT / 'automation-monitoring'

TITLE = 'Automation Monitoring — We Catch What Only Looks Fine'
DESC = ('Your automations can fail while reporting success. We watch them weekly and '
        'send an evidence report — freshness, real content, actual change.')
CANON = 'https://automatedworkflowllc.com/automation-monitoring/'

PAGE_CSS = """
/* ---- monitoring service ---- */
.am-lede{max-width:41rem;font-size:1.05rem}
.am-story{border-left:4px solid #B4452C;background:var(--card);border-radius:.6rem;
padding:1.1rem 1.3rem;margin:1.6rem 0;max-width:44rem}
.am-story .when{font-family:var(--mono);font-size:.75rem;color:var(--ink-soft)}
.am-checks{display:grid;gap:.7rem;grid-template-columns:repeat(auto-fit,minmax(15rem,1fr));margin:1.2rem 0 0}
.am-check{border:1px solid var(--line);border-radius:.7rem;padding:.9rem 1.1rem;background:var(--bg-soft)}
.am-check b{font-family:var(--mono);font-size:.85rem;display:block;margin-bottom:.25rem}
.am-check.hot{border-color:var(--line-strong);background:var(--card)}
.am-check span{font-size:.88rem;color:var(--ink-soft)}
.am-frame{border:1px solid var(--line-strong);border-radius:12px;background:var(--card);
padding:1.3rem 1.5rem;margin:1.3rem 0}
.am-frame .cap{font-size:.8rem;color:var(--ink-soft);margin:0 0 .8rem;font-family:var(--mono)}
.am-frame .verdict{border:1px solid var(--line-strong);border-left:6px solid #B4452C;border-radius:.5rem;
background:var(--bg-soft);padding:.8rem 1rem;font-weight:700;margin:0 0 .8rem}
.am-frame .w{background:var(--bg-soft);border:1px solid var(--line);border-radius:.5rem;
padding:.7rem .95rem;margin:0 0 .5rem}
.am-frame .hd{display:flex;gap:.55rem;align-items:baseline;flex-wrap:wrap}
.am-frame .nm{font-weight:600}
.am-frame code{font-family:var(--mono);font-size:.75rem;color:var(--ink-soft)}
.am-frame p{margin:.3rem 0 0;font-size:.86rem;color:var(--ink-soft)}
.am-frame .mt{margin-top:.25rem;font-size:.74rem;color:var(--ink-soft);font-family:var(--mono)}
.am-price{display:grid;gap:.8rem;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));margin:1.2rem 0 0}
.am-tier{border:1px solid var(--line);border-radius:.8rem;background:var(--card);padding:1.1rem 1.25rem}
.am-tier b{font-size:1.25rem;font-family:var(--mono)}
.am-tier .per{font-size:.8rem;color:var(--ink-soft)}
.am-tier ul{margin:.5rem 0 0;padding-left:1.1rem;font-size:.88rem;color:var(--ink-soft)}
.am-tier li{margin:.2rem 0}
.am-cta{margin-top:1.8rem;padding:1.4rem;border:1px solid var(--line);border-radius:12px;background:var(--bg-soft)}
.am-cta p{margin:.2rem 0 .9rem;color:var(--ink-soft)}
"""

MAIN_TOP = """
<main id="main" class="wrap" style="padding-top:2.2rem;padding-bottom:3rem;max-width:52rem">
  <h1 style="margin-bottom:.4rem">Your automations can fail<br>while reporting success.</h1>
  <p class="am-lede" style="color:var(--ink-soft)">
    The expensive failures don't throw errors. The backup writes a file &mdash; empty. The report
    arrives on time &mdash; with last week's numbers. The sync says "done" &mdash; having synced
    nothing. Normal monitoring can't see any of this, because normal monitoring checks whether the
    job <em>ran</em>, not whether it <em>produced</em>.
  </p>

  <div class="am-story">
    <p class="when">2026-08-03 · 16:52 · our own machine</p>
    <p style="margin:.3rem 0 0"><strong>This happened to us the day we built this page.</strong>
    Our own trading digest fired on schedule, wrote its output file, and passed every freshness
    check we had &mdash; while serving <em>Friday's</em> data under <em>Monday's</em> timestamp.
    An AI summary layer then narrated three-day-old prices in the present tense, confidently.
    Every monitor said healthy, because every monitor judged the file, not the content.
    The report below is the catch, from the tool we built the same afternoon.</p>
  </div>

  <h2>What we check that others don't</h2>
  <div class="am-checks">
    <div class="am-check"><b>MISSING / EMPTY</b><span>The output exists and isn't a 0-byte file
      &mdash; the classic backup that has "succeeded" nightly for months.</span></div>
    <div class="am-check"><b>STALE-FILE</b><span>Written recently enough. This is the one check
      everyone does &mdash; necessary, nowhere near sufficient.</span></div>
    <div class="am-check hot"><b>STALE-CONTENT</b><span>The newest date <em>inside</em> the file
      matches when it was written. A fresh timestamp over old data passes every normal monitor.
      This is the check that caught our own incident.</span></div>
    <div class="am-check hot"><b>FROZEN</b><span>The content actually changes between runs. A
      report rewritten byte-identical for a week is a report nobody is feeding.</span></div>
  </div>

  <h2 style="margin-top:2.2rem">The weekly evidence report</h2>
  <p style="max-width:41rem;color:var(--ink-soft)">This is a real one &mdash; the actual catch from
  our own stack, generated by the same engine that would watch yours. Paths generalized; findings
  verbatim.</p>

  <div class="am-frame">
    <p class="cap">watchpost v0.1.0 · generated 2026-08-03 17:04 · client: our own trading stack</p>
REPORT_ROWS
  </div>
"""

MAIN_BOTTOM = """
  <h2 style="margin-top:2.2rem">Plans</h2>
  <div class="am-price">
    <div class="am-tier">
      <b>$99</b><span class="per">/month &mdash; Watch</span>
      <ul>
        <li>Up to 10 watched outputs (reports, backups, exports, syncs)</li>
        <li>Weekly evidence report to your inbox</li>
        <li>Same-day email when something goes quiet</li>
      </ul>
    </div>
    <div class="am-tier">
      <b>$225</b><span class="per">/month &mdash; Watch + fix</span>
      <ul>
        <li>Everything in Watch</li>
        <li>We fix what we catch &mdash; up to 2 hours of repair a month included</li>
        <li>Quarterly deep audit of the whole automation stack</li>
      </ul>
    </div>
  </div>
  <p style="max-width:41rem;color:var(--ink-soft);font-size:.9rem;margin-top:.8rem">
    Honest scope: this watches <em>outputs on your systems</em> &mdash; files, exports, reports.
    If your stack is entirely inside SaaS tools with no exportable output, this isn't the right
    fit yet, and we'll say so on the first call rather than after the first invoice.</p>

  <div class="am-cta">
    <h2 style="margin-top:0">Start with the free version of the question</h2>
    <p>Not ready for a retainer? Fair. The one-shot version of this check is free and open source
      &mdash; <a href="/flatline/">flatline</a> finds what's already quietly dead. Or send one
      suspicious export through the <a href="/check/">free file check</a> right now.</p>
    <p style="margin-bottom:0"><a class="btn" href="/free-demo/">Ask about monitoring</a>
      &nbsp; <a href="/builds/">See everything we've built &rarr;</a></p>
  </div>
</main>
"""

LD = """
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Service",
  "name": "Automation Monitoring",
  "url": "https://automatedworkflowllc.com/automation-monitoring/",
  "provider": { "@type": "Organization", "name": "Automated Workflow" },
  "description": "Weekly monitoring of business automations with an evidence report: outputs exist, are fresh, contain current data, and actually change between runs.",
  "offers": [
    { "@type": "Offer", "price": "99", "priceCurrency": "USD", "description": "Watch: up to 10 outputs, weekly evidence report" },
    { "@type": "Offer", "price": "225", "priceCurrency": "USD", "description": "Watch + fix: repairs included, quarterly deep audit" }
  ]
}
</script>
"""


def main() -> None:
    demo = DEMO_REPORT.read_text(encoding='utf-8')
    m = re.search(r'<div class="verdict".*?(?=<footer>)', demo, re.S)
    if not m:
        raise SystemExit('demo-report.html shape changed -- refusing to embed garbage')
    rows = m.group(0)
    # Re-home the report's classes onto this page's tokens: the report ships
    # standalone colors; embedded, it must inherit the site shell instead.
    rows = re.sub(r'<div class="verdict"[^>]*>', '<div class="verdict">', rows)
    if 'hisbo' in rows or 'C:\\' in rows:
        raise SystemExit('internal machine paths leaked into the embedded report -- fix before shipping')

    s = TEMPLATE.read_text(encoding='utf-8')
    head = s[:s.index('</header>') + len('</header>')]
    footer = s[s.index('<footer'):s.index('</footer>') + len('</footer>')]

    head = re.sub(r'<title>.*?</title>', f'<title>{TITLE}</title>', head, flags=re.S)
    head = re.sub(r'(<meta name="description" content=").*?(">)', rf'\g<1>{DESC}\g<2>', head)
    head = re.sub(r'(<link rel="canonical" href=").*?(">)', rf'\g<1>{CANON}\g<2>', head)
    head = re.sub(r'(<meta property="og:title" content=").*?(">)', rf'\g<1>{TITLE}\g<2>', head)
    head = re.sub(r'(<meta property="og:description" content=").*?(">)', rf'\g<1>{DESC}\g<2>', head)
    head = re.sub(r'(<meta property="og:url" content=").*?(">)', rf'\g<1>{CANON}\g<2>', head)
    head = head.replace('</head>', f'<style>{PAGE_CSS}</style>\n</head>')

    body = MAIN_TOP.replace('REPORT_ROWS', rows) + MAIN_BOTTOM
    page = head + body + footer + LD + '\n</body>\n</html>\n'
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / 'index.html').write_text(page, encoding='utf-8')
    print(f'wrote {OUT_DIR / "index.html"} ({len(page)} bytes)')


if __name__ == '__main__':
    main()
