# -*- coding: utf-8 -*-
"""One palette, one type scale, one spacing rhythm -- for every page.

WHY THIS EXISTS. Measured 2026-08-11: every page on this site declared its own
CSS custom properties and NONE shared a source. The homepage used --ink #1F1C15
while its own tools used #211D14 -- close enough that nobody consciously notices,
far enough that the pages feel subtly unrelated. skeleton was blueprint navy and
almanac warm brass. Three different companies, one domain.

That is the same defect as the duplicated parser and the three-copy test harness,
in the design layer: no single source, so agreement is luck and drift is
guaranteed. The fix is the same shape. After this, a new tool CANNOT be off-brand,
because it does not declare its own colours.

THE DIRECTION, and why each choice rather than the obvious one:

  GROUND -- warm off-black and warm parchment, never neutral grey. Almost every
  developer-tool site is cool grey or pure black; warm reads as chosen. A pure
  mid-grey reads as unconsidered, so every neutral here carries a slight hue bias
  toward the accent.

  ACCENT -- a single brass. It appears on interactive things and on the one number
  you are meant to look at, and nowhere else. Restraint is what makes an accent
  read as expensive; using it everywhere is what makes a page look like a demo.

  SEMANTIC -- good/warn/bad are SEPARATE from the accent and never borrow it. A
  page where "success" and "this link" are the same colour cannot show a clean
  result and a call to action at the same time.

  TYPE -- one scale. Tracking tightens as size grows, which keeps large text from
  looking loose and small text from looking cramped; tabular figures wherever
  digits line up in a column.

  NOT USED, deliberately: gradients, glassmorphism, purple-to-blue heroes. Those
  read as machine-generated in 2026 and would undercut the only thing this site
  actually sells, which is that the work is careful.
"""

# Both themes are defined here rather than one in a media query, so a colour can
# never exist in one theme and be missing in the other -- the failure that leaves
# a dark-mode page with invisible text.
LIGHT = {
    'bg':          '#F5F3ED',   # warm parchment, not white
    'panel':       '#FFFDF8',
    'well':        '#EAE6DA',
    'sunk':        '#E2DDCE',
    'ink':         '#191713',   # warm near-black
    'ink-2':       '#3D3934',
    'mut':         '#6B6459',
    'faint':       '#938A7B',
    'line':        '#DDD8CA',
    'rule':        '#C2BAA7',
    'accent':      '#8A6413',   # brass, dark enough for AA on parchment
    'accent-2':    '#B99334',
    'accent-wash': '#EFE4C6',
    'ok':          '#2A6A4F',
    'warn':        '#95610F',
    'bad':         '#98283C',
}

DARK = {
    'bg':          '#12100C',
    'panel':       '#1A1712',
    'well':        '#221E17',
    'sunk':        '#2A251C',
    'ink':         '#F0EBE0',
    'ink-2':       '#D3CCBD',
    'mut':         '#9A9184',
    'faint':       '#6E675C',
    'line':        '#2B261E',
    'rule':        '#443D31',
    'accent':      '#E3BE6A',   # lifted for contrast on the dark ground
    'accent-2':    '#A5813A',
    'accent-wash': '#332A18',
    'ok':          '#63BC96',
    'warn':        '#DFA544',
    'bad':         '#E4798D',
}

SCALE = """
  /* type -- sizes in rem so a reader's own setting still wins */
  --f-xs: .72rem;   --f-sm: .82rem;   --f-md: .93rem;   --f-base: 1rem;
  --f-lg: 1.15rem;  --f-xl: 1.45rem;  --f-2xl: 1.9rem;  --f-3xl: 2.4rem;
  --track-tight: -.022em;  --track-snug: -.012em;  --track-wide: .09em;
  --lh-tight: 1.18;  --lh-snug: 1.35;  --lh-body: 1.6;

  /* spacing -- one rhythm. Every gap on every page is one of these, which is
     most of what separates "designed" from "assembled". */
  --s-1: .25rem; --s-2: .45rem; --s-3: .7rem;  --s-4: 1rem;
  --s-5: 1.4rem; --s-6: 2rem;   --s-7: 2.8rem; --s-8: 4rem;

  --radius: .6rem;  --radius-sm: .35rem;
  --measure: 68ch;          /* longest comfortable line of body text */

  --mono: ui-monospace, "SF Mono", SFMono-Regular, Menlo, Consolas, monospace;
  --sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto,
          Helvetica, Arial, sans-serif;
"""


def _vars(d, indent='  '):
    return '\n'.join('%s--%s: %s;' % (indent, k, v) for k, v in d.items())


def css():
    """The token block, emitted into every page by the builders.

    Theme handling is deliberate: the palette is defined on bare :root, redefined
    under prefers-color-scheme for the OS default, and redefined AGAIN under
    [data-theme] so an explicit toggle beats the media query in both directions.
    A colour defined only inside a media query is how a page ends up unreadable
    for the half of visitors on the other setting.
    """
    return (
        "/* Generated by _brand/tokens.py -- do not edit in the page.\n"
        "   One palette, one scale. A page that declares its own colours has\n"
        "   opted out of the design system and will drift. */\n"
        ":root {\n" + _vars(LIGHT) + "\n" + SCALE + "}\n"
        "@media (prefers-color-scheme: dark) {\n"
        "  :root:not([data-theme=\"light\"]) {\n" + _vars(DARK, '    ') + "\n  }\n}\n"
        ":root[data-theme=\"dark\"] {\n" + _vars(DARK) + "\n}\n"
        ":root[data-theme=\"light\"] {\n" + _vars(LIGHT) + "\n}\n"
    )


def contrast(hex_a, hex_b):
    """WCAG contrast ratio, so the palette can be CHECKED rather than admired. A
    brass that looks lovely and fails AA on body text is a bug, not a taste."""
    def lum(h):
        h = h.lstrip('#')
        parts = [int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4)]
        parts = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in parts]
        return 0.2126 * parts[0] + 0.7152 * parts[1] + 0.0722 * parts[2]
    a, b = lum(hex_a), lum(hex_b)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


if __name__ == '__main__':
    print(css())
